# Dockerfile for building and serving the Angular se application.

# ------------------------------
# Stage 1: Build the Angular app
# ------------------------------
FROM node:22-slim AS node
WORKDIR /app

# --- Copy dependency configuration files first --- 
COPY *.json ./

# --- Install dependencies ---
# Install pnpm globally, configure its global binary directory,
# install Nx CLI, install project dependencies and add webpack.
RUN npm install -g pnpm && \
    mkdir -p /pnpm-global && \
    pnpm config set prefix "/pnpm-global/bin" && \
    export PNPM_HOME=/pnpm-global/bin && \
    export PATH=$PNPM_HOME:$PATH && \
    pnpm add -g nx && \
    pnpm install --no-lockfile && \
    pnpm add webpack@5.91.0

# --- Copy the application source code ---
COPY apps ./apps
COPY libs ./libs

# ------------------------------
# Clean build and cache directories before build
# ------------------------------
RUN rm -rf node_modules/.cache dist .angular/cache

# Enable verbose logging for Nx.
ENV NX_VERBOSE_LOGGING=true

ARG NODE_ENV
RUN echo "Building se image for environment: $NODE_ENV"
# Build the se application using Nx.
ENV NODE_OPTIONS=--max-old-space-size=10096
RUN npx nx build se --configuration=$NODE_ENV --base-href=/se/ --skip-nx-cache --verbose

# ------------------------------
# Stage 2: Serve with Nginx
# ------------------------------
FROM nginx:alpine-slim
# Copy custom Nginx configuration for the se.
COPY ./apps/se/nginx.conf /etc/nginx/nginx.conf
# Copy the built se application from Stage 1 to the Nginx-served directory.
COPY --from=node /app/dist/apps/se /usr/share/nginx/html
