export const DATOS_DE_LA_SOLICICTUD = {
  AUTOR: 'Autor',
  TITULO: 'Titulo',
  TECNICA_DE_REALIZACION: 'Técnica de realización',
  CON_MARCO: 'Con marco',
  ANCHO: 'Ancho (centímetros)',
  ALTO: 'Alto (centímetros)',
  PROFUNDIDAD: 'Profunded (centímetros)',
  DIAMETRO: 'Diametro (centímetros)',
  VARIABLES: 'Variables',
  ANO_DE_CREACION: 'Año de creación',
  AVALUO: 'Avalúo',
  MONEDA: 'Moneda',
  PROPIETARIO: 'Propietario',
  FRACCION_ARANCELARIA: 'Fracción arancelaria',
  DESCRIPCION: 'Descripción de la fracción arancelaria',
};

export const INFORMACION_DE_LA_OBRA_ARTE = [
  {
    id: 'autor',
    labelNombre: 'Autor',
    campo: 'autor',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'titulo',
    labelNombre: 'Titulo',
    campo: 'titulo',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Inserta titulo',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'technicaDeRealizacion',
    labelNombre: 'Técnica de realización',
    campo: 'technicaDeRealizacion',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Inserta técnica de realización',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'medidas',
    labelNombre: 'Medidas',
    campo: 'medidas',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: 'con',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Con marco',
        value: 'con',
      },
      {
        label: 'Sin marco',
        value: 'sin',
      },
    ],
  },
  {
    id: 'alto',
    labelNombre: 'Alto (centímetros)',
    campo: 'alto',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'ancho',
    labelNombre: 'Ancho (centímetros)',
    campo: 'ancho',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'profundidad',
    labelNombre: 'Profundidad (centímetros)',
    campo: 'profundidad',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'diametro',
    labelNombre: 'Diametro (centímetros)',
    campo: 'diametro',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'variables',
    labelNombre: 'Variables',
    campo: 'variables',
    clase: 'col-md-8',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Inserta variables',
    valorPredeterminado: '',
    marginTop: 0,
  },
//   {
//     id: '',
//     labelNombre: '',
//     campo: '',
//     clase: 'col-md-4',
//     tipoInput: '',
//     desactivado: false,
//     soloLectura: false,
//     validadores: [],
//     marcadorDePosicion: '',
//     valorPredeterminado: '',
//     marginTop: 0,
//   },
];

export const PERIODO_EN_EL_QUE_PERMANECERA = [
    {
        id: 'fecha_inicio',
        labelNombre: 'Fecha inicio',
        campo: 'fecha_inicio',
        clase: 'col-md-4',
        tipoInput: 'date',
        desactivado: false,
        soloLectura: false,
        validadores: [
            { tipo: 'required' }
        ],
        marcadorDePosicion: '',
        valorPredeterminado: '',
        marginTop: 0,
    },
]

export const OBRA_DE_ARTE_ALERT =
  'Nota: Es indispensable proporcionar las medidas de cada pieza, ya que de no hacerlo se puede afectar la dictaminación de su solicitud';
