export const DATOS_DE_LA_SOLICICTUD = {
  AUTOR: 'Autor',
  TITULO: 'Titulo',
  TECNICA_DE_REALIZACION: 'Técnica de realización',
  CON_MARCO: 'Con marco',
  ANCHO: 'Ancho (centímetros)',
  ALTO: 'Alto (centímetros)',
  PROFUNDIDAD: 'Profunded (centímetros)',
  DIAMETRO: 'Diametro (centímetros)',
  VARIABLES: 'Variables',
  ANO_DE_CREACION: 'Año de creación',
  AVALUO: 'Avalúo',
  MONEDA: 'Moneda',
  PROPIETARIO: 'Propietario',
  FRACCION_ARANCELARIA: 'Fracción arancelaria',
  DESCRIPCION: 'Descripción de la fracción arancelaria',
};

export const INFORMACION_DE_LA_OBRA_ARTE = [
  {
    id: 'autor',
    labelNombre: 'Autor',
    campo: 'autor',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'titulo',
    labelNombre: 'Titulo',
    campo: 'titulo',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Inserta titulo',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'technicaDeRealizacion',
    labelNombre: 'Técnica de realización',
    campo: 'technicaDeRealizacion',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Inserta técnica de realización',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'medidas',
    labelNombre: 'Medidas',
    campo: 'medidas',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: 'con',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Con marco',
        value: 'con',
      },
      {
        label: 'Sin marco',
        value: 'sin',
      },
    ],
  },
  {
    id: 'alto',
    labelNombre: 'Alto (centímetros)',
    campo: 'alto',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'ancho',
    labelNombre: 'Ancho (centímetros)',
    campo: 'ancho',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'profundidad',
    labelNombre: 'Profundidad (centímetros)',
    campo: 'profundidad',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'diametro',
    labelNombre: 'Diametro (centímetros)',
    campo: 'diametro',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'variables',
    labelNombre: 'Variables',
    campo: 'variables',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Inserta variables',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: '',
    labelNombre: '',
    campo: '',
    clase: 'col-md-4',
    tipoInput: '',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
];

export const PERIODO_EN_EL_QUE_PERMANECERA = [
    {
        id: 'fecha_inicio',
        labelNombre: 'Fecha inicio',
        campo: 'fecha_inicio',
        clase: 'col-md-4',
        tipoInput: 'date',
        desactivado: false,
        soloLectura: false,
        validadores: [
            { tipo: 'required' }
        ],
        marcadorDePosicion: '',
        valorPredeterminado: '',
        marginTop: 0,
        habilitado: true
    },
    {
      id: 'fecha_fin',
      labelNombre: 'Fecha fin',
      campo: 'fecha_fin',
      clase: 'col-md-4',
      tipoInput: 'date',
      desactivado: false,
      soloLectura: false,
      validadores: [
          { tipo: 'required' }
      ],
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      habilitado: true
  },
  {
    id: 'responsable_exportacion',
    labelNombre: 'Responsable de la exportación',
    campo: 'responsable_exportacion',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  }
]

export const MOTIVO_DE_LA_EXPORTACION = [
  {
    id: 'motivo',
    labelNombre: 'Motivo',
    campo: 'motivo',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'nombre',
    labelNombre: 'Nombre',
    campo: 'nombre',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    mostrar: false
  },
]

export const LUGAR_DE_DESTINO = [
  {
    id: 'pais',
    labelNombre: 'País',
    campo: 'pais',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'ciudad',
    labelNombre: 'Ciudad',
    campo: 'ciudad',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0
  },
  {
    id: 'sede',
    labelNombre: 'Sede',
    campo: 'sede',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0
  },
]

export const ITINERARIO_DE_EXPORTACION = [
  {
    id: 'tipoItinerario',
    labelNombre: 'Tipo itinerario',
    campo: 'tipoItinerario',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: true,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '1',
    marginTop: 0,
    opciones: [
      {
        id: 1, descripcion: 'Traslado'
      }
    ]
  },
  {
    id: 'ciudad',
    labelNombre: 'Ciudad',
    campo: 'ciudad',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0
  },
  {
    id: '',
    labelNombre: '',
    campo: '',
    clase: 'col-md-4',
    tipoInput: '',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0
  },
  {
    id: 'tipoDeTraslado',
    labelNombre: 'Tipo de traslado',
    campo: 'tipoDeTraslado',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0
  },
  {
    id: 'observaciones',
    labelNombre: 'Observaciones',
    campo: 'observaciones',
    clase: 'col-md-8',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0
  },
  {
    id: 'fechaInicio',
    labelNombre: 'Fecha inicio',
    campo: 'fechaInicio',
    clase: 'col-md-4',
    tipoInput: 'date',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    habilitado: true
  },
  {
    id: 'fechaFin',
    labelNombre: 'Fecha fin',
    campo: 'fechaFin',
    clase: 'col-md-4',
    tipoInput: 'date',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    habilitado: true
  },
]

export const ITINERARIO_DE_EXPORTACION_MAXIMO = [
  {
    id: 'tipoItinerario',
    labelNombre: 'Tipo itinerario',
    campo: 'tipoItinerario',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: true,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '1',
    marginTop: 0,
    opciones: [
      {
        id: 1, descripcion: 'Traslado'
      }
    ]
  },
  {
    id: 'ciudad',
    labelNombre: 'Ciudad',
    campo: 'ciudad',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0
  },
  {
    id: 'nombre',
    labelNombre: 'Nombre de Sede',
    campo: 'nombre',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0
  },
  {
    id: 'observaciones',
    labelNombre: 'Observaciones',
    campo: 'observaciones',
    clase: 'col-md-9',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0
  },
  {
    id: 'fechaDeExhibicion',
    labelNombre: 'Fecha de exhibicion',
    campo: 'fechaDeExhibicion',
    clase: 'col-md-4',
    tipoInput: 'date',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    habilitado: true
  },
  {
    id: 'fechaInicio',
    labelNombre: 'Fecha inicio',
    campo: 'fechaInicio',
    clase: 'col-md-4',
    tipoInput: 'date',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    habilitado: true
  },
  {
    id: 'fechaFin',
    labelNombre: 'Fecha fin',
    campo: 'fechaFin',
    clase: 'col-md-4',
    tipoInput: 'date',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    habilitado: true
  },
]

export const PAGO_DE_DERECHOS = [
  {
    id: 'claveDeReferencia',
    labelNombre: 'Clave de referencia',
    campo: 'claveDeReferencia',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '144000786',
    marginTop: 0
  },
  {
    id: 'cadenaDeLaDependencia',
    labelNombre: 'Cadena de la dependencia',
    campo: 'cadenaDeLaDependencia',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '04055740400001',
    marginTop: 0
  },
  {
    id: 'banco',
    labelNombre: 'Banco',
    campo: 'banco',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '',
    marginTop: 0
  },
  {
    id: 'llaveDePago',
    labelNombre: 'Llave de pago',
    campo: 'llaveDePago',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0
  },
  {
    id: 'fechaDePago',
    labelNombre: 'Fecha de pago',
    campo: 'fechaDePago',
    clase: 'col-md-4',
    tipoInput: 'date',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    habilitado: true
  },
  {
    id: 'importeDePago',
    labelNombre: 'Importe de pago',
    campo: 'importeDePago',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '40',
    marginTop: 0
  },
]

export const OBRA_DE_ARTE_ALERT =
  'Nota: Es indispensable proporcionar las medidas de cada pieza, ya que de no hacerlo se puede afectar la dictaminación de su solicitud';

export const ADUANA_ALERT =
'Agrega los datos del traslado y, posteriormente, siguiendo el mismo proceso, agrega la sede. A cada traslado le corresponde una sede (máximo 2 itinerarios).';

export const ERROR_DE_REGISTRO_ALERT =
'<strong>¡Error de registro! </strong>En el itinerario de la exportación y transportacion a cada translado le corresponde una sede.';

export const ERROR_FORMA_ALERT =
'<strong>¡Error de registro! </strong>Faltan campos por capturar.';
