export const DATOS_DE_LA_SOLICICTUD = {
  AUTOR: 'Autor',
  TITULO: 'Titulo',
  TECNICA_DE_REALIZACION: 'Técnica de realización',
  CON_MARCO: 'Con marco',
  ANCHO: 'Ancho (centímetros)',
  ALTO: 'Alto (centímetros)',
  PROFUNDIDAD: 'Profunded (centímetros)',
  DIAMETRO: 'Diametro (centímetros)',
  VARIABLES: 'Variables',
  ANO_DE_CREACION: 'Año de creación',
  AVALUO: 'Avalúo',
  MONEDA: 'Moneda',
  PROPIETARIO: 'Propietario',
  FRACCION_ARANCELARIA: 'Fracción arancelaria',
  DESCRIPCION: 'Descripción de la fracción arancelaria',
};

export const INFORMACION_DE_LA_OBRA_ARTE = [
  {
    id: 'autor',
    label_nombre: 'Autor',
    campo: 'autor',
    clase: 'col-md-4',
    tipo_input: 'select-catalogos',
    desactivado: false,
    solo_lectura: false,
    validadores: [{ tipo: 'required' }],
    marcador_de_posicion: 'Selecciona un valor',
    valor_predeterminado: '',
    margin_top: 0,
  },
  {
    id: 'titulo',
    label_nombre: 'Titulo',
    campo: 'titulo',
    clase: 'col-md-4',
    tipo_input: 'text',
    desactivado: false,
    solo_lectura: false,
    validadores: [{ tipo: 'required' }],
    marcador_de_posicion: 'Inserta titulo',
    valor_predeterminado: '',
    margin_top: 0,
  },
  {
    id: 'technicaDeRealizacion',
    label_nombre: 'Técnica de realización',
    campo: 'technicaDeRealizacion',
    clase: 'col-md-4',
    tipo_input: 'text',
    desactivado: false,
    solo_lectura: false,
    validadores: [{ tipo: 'required' }],
    marcador_de_posicion: 'Inserta técnica de realización',
    valor_predeterminado: '',
    margin_top: 0,
  },
  {
    id: 'medidas',
    label_nombre: 'Medidas',
    campo: 'medidas',
    clase: 'col-md-12',
    tipo_input: 'radio',
    desactivado: false,
    solo_lectura: false,
    validadores: [{ tipo: 'required' }],
    valor_predeterminado: 'con',
    marcador_de_posicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Con marco',
        value: 'con',
      },
      {
        label: 'Sin marco',
        value: 'sin',
      },
    ],
  },
  {
    id: 'alto',
    label_nombre: 'Alto (centímetros)',
    campo: 'alto',
    clase: 'col-md-4',
    tipo_input: 'number',
    desactivado: false,
    solo_lectura: false,
    validadores: [],
    marcador_de_posicion: '0.00',
    valor_predeterminado: '',
    margin_top: 0,
  },
  {
    id: 'ancho',
    label_nombre: 'Ancho (centímetros)',
    campo: 'ancho',
    clase: 'col-md-4',
    tipo_input: 'number',
    desactivado: false,
    solo_lectura: false,
    validadores: [],
    marcador_de_posicion: '0.00',
    valor_predeterminado: '',
    margin_top: 0,
  },
  {
    id: 'profundidad',
    label_nombre: 'Profundidad (centímetros)',
    campo: 'profundidad',
    clase: 'col-md-4',
    tipo_input: 'number',
    desactivado: false,
    solo_lectura: false,
    validadores: [],
    marcador_de_posicion: '0.00',
    valor_predeterminado: '',
    margin_top: 0,
  },
  {
    id: 'diametro',
    label_nombre: 'Diametro (centímetros)',
    campo: 'diametro',
    clase: 'col-md-4',
    tipo_input: 'number',
    desactivado: false,
    solo_lectura: false,
    validadores: [],
    marcador_de_posicion: '0.00',
    valor_predeterminado: '',
    margin_top: 0,
  },
  {
    id: 'variables',
    label_nombre: 'Variables',
    campo: 'variables',
    clase: 'col-md-8',
    tipo_input: 'text',
    desactivado: false,
    solo_lectura: false,
    validadores: [{ tipo: 'required' }],
    marcador_de_posicion: 'Inserta variables',
    valor_predeterminado: '',
    margin_top: 0,
  },
//   {
//     id: '',
//     label_nombre: '',
//     campo: '',
//     clase: 'col-md-4',
//     tipo_input: '',
//     desactivado: false,
//     solo_lectura: false,
//     validadores: [],
//     marcador_de_posicion: '',
//     valor_predeterminado: '',
//     margin_top: 0,
//   },
];

export const PERIODO_EN_EL_QUE_PERMANECERA = [
    {
        id: 'fecha_inicio',
        label_nombre: 'Fecha inicio',
        campo: 'fecha_inicio',
        clase: 'col-md-4',
        tipo_input: 'date',
        desactivado: false,
        solo_lectura: false,
        validadores: [
            { tipo: 'required' }
        ],
        marcador_de_posicion: '',
        valor_predeterminado: '',
        margin_top: 0,
    },
]

export const OBRA_DE_ARTE_ALERT =
  'Nota: Es indispensable proporcionar las medidas de cada pieza, ya que de no hacerlo se puede afectar la dictaminación de su solicitud';
