export enum choferesEnum {
    solicitudTituloChoferExtranjero = 'Datos del chofer extranjero',
    labelSolicitudPersonaNombre = 'Nombre',
    labelSolicitudPersonaPrimerApellido = 'Primer Apellido',
    labelSolicitudPersonaSegundoApellido = 'Segundo Apellido',
    labelNacionalidad = 'Nacionalidad',
    labelSolicitudChoferExtGafete = 'Numero de gafete del chofer',
    labelSolicitudChoferExtVigenciaGafete = 'Vigencia del Gafete',
    labelSolicitudChoferExtNss = 'Número de Seguro Social (NSS)',
    labelSolicitudChoferExtIdeFiscal = 'Número de Identificación Fiscal',
    tooltipIdentificacionFiscal = 'Número de identificación fiscal en el país de residencia',
    solicitudTituloDomicilioFiscal = 'Domicilio Fiscal',
    labelPais = 'País',
    labelSolicitudDomicilioCodigoPostal = 'Código Postal',
    labelEntidadFederativa = 'Estado',
    labelSolicitudDomicilioCalle = 'Calle',
    labelSolicitudDomicilioNumeroExterior = 'Número exterior',
    labelSolicitudDomicilioNumeroInterior = 'Número interior',
    labelPaisOrigen = 'País de residencia',
    labelSolicitudDomicilioCiudad = 'Ciudad',
    labelSolicitudCorreo = 'Correo electrónico',
    labelSolicitudTelefono = 'Teléfono',
    camposObligatorios = '* Campos obligatorios',
    botonBuscar = 'Buscar',
    botonLimpiar = 'Limpiar',
    botonCancelar = 'Cancelar',
    botonGuardar = 'Guardar',
    seleccionaUnValor = 'Selecciona un valor',
    labelPuntos = '...'
  }
  