export const PAGO_DE_DERECHOS = [
  {
    id: 'claveReferencia',
    labelNombre: 'Clave de referencia',
    campo: 'claveReferencia',
    clase: 'col-md-6',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
  },
  {
    id: 'numeroOperacion',
    labelNombre: 'Número de operación',
    campo: 'numeroOperacion',
    clase: 'col-md-6',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
  },
  {
    id: 'cadenaDependencia',
    labelNombre: 'Cadena de la dependencia',
    campo: 'cadenaDependencia',
    clase: 'col-md-6',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
  },
  {
    id: 'banco',
    labelNombre: 'Banco',
    campo: 'banco',
    clase: 'col-md-6',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
  },
  {
    id: 'llaveDePago',
    labelNombre: 'Llave de pago',
    campo: 'llaveDePago',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
  },
  {
    id: 'fechaDepago',
    labelNombre: 'Fecha de pago',
    campo: 'fechaDepago',
    clase: 'col-md-4',
    tipoInput: 'date',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    habilitado: true,
  },
  {
    id: 'importeDepago',
    labelNombre: 'Importe de pago',
    campo: 'importeDepago',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
  },
];