server {
    listen 80;

    # La raíz de la aplicación está en /usr/share/nginx/html
    root /usr/share/nginx/html;
    index index.html;

    # Asegura que cualquier ruta desconocida sea dirigida al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configuración para archivos estáticos (puedes ajustarlo según el caso)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|otf|webp)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Bloqueo de acceso a archivos ocultos
    location ~ /\. {
        deny all;
    }
}
