export const EXPEDICION_CERTIFICADOS_FRONTERA = [
  {
    indice: 1,
    titulo: 'Capturar solicitud',
    activo: true,
    completado: true,
  },
  {
    indice: 2,
    titulo: 'Firmar solicitud',
    activo: false,
    completado: false,
  },
];

export const INPUT_FECHA_INICIO = {
  labelNombre: 'Fecha inicio',
  required: false,
  habilitado: true,
};

export const INPUT_FECHA_FIN = {
  labelNombre: 'Fecha fin',
  required: false,
  habilitado: true,
};

export const INPUT_FECHA_INICIO_CUPO = {
  labelNombre: 'Fecha inicio vigencia del cupo',
  required: false,
  habilitado: true,
};

export const INPUT_FECHA_FIN_CUPO = {
  labelNombre: 'Fecha fin vigencia del cupo',
  required: false,
  habilitado: true,
};

export const INFORMACION_DE_LA_OBRA_ARTE = [
  {
    id: 'autor',
    labelNombre: 'Autor',
    campo: 'autor',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'titulo',
    labelNombre: 'Titulo',
    campo: 'titulo',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Inserta titulo',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'technicaDeRealizacion',
    labelNombre: 'Técnica de realización',
    campo: 'technicaDeRealizacion',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Inserta técnica de realización',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'medidas',
    labelNombre: 'Medidas',
    campo: 'medidas',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: 'con',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Con marco',
        value: 'con',
      },
      {
        label: 'Sin marco',
        value: 'sin',
      },
    ],
  },
  {
    id: 'alto',
    labelNombre: 'Alto (centímetros)',
    campo: 'alto',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'ancho',
    labelNombre: 'Ancho (centímetros)',
    campo: 'ancho',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'profundidad',
    labelNombre: 'Profundidad (centímetros)',
    campo: 'profundidad',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'diametro',
    labelNombre: 'Diametro (centímetros)',
    campo: 'diametro',
    clase: 'col-md-4',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '0.00',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'variables',
    labelNombre: 'Variables',
    campo: 'variables',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Inserta variables',
    valorPredeterminado: '',
    marginTop: 0,
  }
];