export const CROSLISTA_ADUANAS_DISPONIBLES: string[] = [
  'ACAPULCO, PUERTO Y AEROPUERT',
  'ADUANA DE PANTACO',
  'AEROPUERTO INT. DE LA CD DE MEX',
  'AEROPUERTO INTERNACIONAL FELIP',
  'AGUA PRIETA',
  'AGUASCALIENTES, AGS.',
  'ALTAMIRA',
  'CANCUN, AEROPUERTO',
  'CD. CAMARGO, TAMPS.',
  'CD. DEL CARMEN',
  'CD. JUAREZ',
  'CHIHUAHUA, CHIH.',
];
