export const PANTA_PASOS = [
    {
      indice: 1,
      titulo: 'Capturar solicitud',
      activo: true,
      completado: true,
    },
    {
      indice: 2,
      titulo: 'Anexar requisitos',
      activo: false,
      completado: false,
    },
    {
      indice: 3,
      titulo: 'Firmar solicitud',
      activo: false,
      completado: false,
    },
  ];

  export const INFORMACION_DE_LA_OBRA_ARTE = [
    {
      id: 'Folio trámite',
      row: 1,
      labelNombre: 'Folio trámite',
      campo: 'Folio trámite',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      // validadores: [{ tipo: 'required' }],
       marcadorDePosicion: '',
      valorPredeterminado: '',
      // marginTop: 0,
      marginTop: 0,
    },
    {
      id: 'Tipo de solicitud',
      row:1,
      labelNombre: 'Tipo de solicitud',
      campo: 'Tipo de solicitud',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      // validadores: [{ tipo: 'required' }],
       marcadorDePosicion: '',
      valorPredeterminado: '',
      // marginTop: 0,
      marginTop: 0,
    },
    {
      id: 'Régimen',
      row:1,
      labelNombre: 'Régimen',
      campo: 'Régimen',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      // validadores: [{ tipo: 'required' }],
       marcadorDePosicion: '',
      valorPredeterminado: '',
      // marginTop: 0,
      marginTop: 0,
    },
    {
      id: 'Clasificación del régimen',
      labelNombre: 'Clasificación del régimen',
      campo: 'Clasificación del régimen',
      clase: 'col-md-4',
      row:2,
      // rows:"2",
      // height:"50px",
      tipoInput: 'textarea',
      desactivado: false,
      soloLectura: false,
      // validadores: [{ tipo: 'required' }],
       marcadorDePosicion: '',
      valorPredeterminado: '',
      // marginTop: 0,
      marginBottom: 0,

    },
    {
      id: 'Periodo de vigencia',
      labelNombre: 'Periodo de vigencia',
      campo: 'Periodo de vigencia',
      clase: 'col-md-4',
      row:2,
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      // validadores: [{ tipo: 'required' }],
       marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'Unidad de medida',
      labelNombre: 'Unidad de medida',
      campo: 'Unidad de medida',
      clase: 'col-md-4',
      tipoInput: 'text',
      row:2,
      desactivado: false,
      soloLectura: false,
      // validadores: [{ tipo: 'required' }],
       marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'Fracción arancelaria',
      labelNombre: 'Fracción arancelaria',
      campo: 'Fracción arancelaria',
      clase: 'col-md-4',
      tipoInput: 'text',
      row:3,
      desactivado: false,
      soloLectura: false,
      // validadores: [{ tipo: 'required' }],
       marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'Cantidad autorizada',
      labelNombre: 'Cantidad autorizada',
      campo: 'Cantidad autorizada',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      row:3,
      // validadores: [{ tipo: 'required' }],
       marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'Valor autorizado',
      labelNombre: 'Valor autorizado',
      campo: 'Valor autorizado',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      row:3,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
    {
      id: 'NICO',
      labelNombre: 'NICO',
      campo: 'nico',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      row:3,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
    {
      id: 'NICO',
      labelNombre: 'NICO',
      campo: 'descripcionNico',
      clase: 'col-md-4',
      tipoInput: 'textarea',
      desactivado: false,
      soloLectura: false,
      row:3,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
    {
      id: 'Acotación',
      labelNombre: 'Acotación',
      campo: 'acotacion',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      row:3,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
    {
      id: 'Permiso válido desde',
      labelNombre: 'Permiso válido desde',
      campo: 'permisoValidoDesde',
      clase: 'col-md-4',
      tipoInput: 'date',
      desactivado: false,
      soloLectura: false,
      row:3,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
    {
      id: 'Permiso válido hasta',
      labelNombre: 'Permiso válido hasta',
      campo: 'permisoValidoHasta',
      clase: 'col-md-4',
      tipoInput: 'date',
      desactivado: false,
      soloLectura: false,
      row:3,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
  ]
  