export const PANTA_PASOS = [
    {
      indice: 1,
      titulo: 'Capturar solicitud',
      activo: true,
      completado: true,
    },
    {
      indice: 2,
      titulo: 'Anexar requisitos',
      activo: false,
      completado: false,
    },
    {
      indice: 3,
      titulo: 'Firmar solicitud',
      activo: false,
      completado: false,
    },
  ];

  export const INFORMACION_DE_LA_OBRA_ARTE = [
    {
      id: 'folioTramite',
      labelNombre: 'Folio trámite',
      campo: 'folioTramite',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
    {
      id: 'tipoSolicitud',
      row:1,
      labelNombre: 'Tipo de solicitud',
      campo: 'tipoSolicitud',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '',
     marginTop: 0,
    },
    {
      id: 'regimen',
      labelNombre: 'Régimen',
      campo: 'regimen',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
    {
      id: 'clasificacionRegimen',
      labelNombre: 'Clasificación del régimen',
      campo: 'clasificacionRegimen',
      clase: 'col-md-4',
      row:2,
      tipoInput: 'textarea',
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginBottom: 0,
},
    {
      id: 'periodoVigencia',
      labelNombre: 'Periodo de vigencia',
      campo: 'periodoVigencia',
      clase: 'col-md-4',
      row:2,
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
     
       marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'unidadMedida',
      labelNombre: 'Unidad de medida',
      campo: 'unidadMedida',
      clase: 'col-md-4',
      tipoInput: 'text',
      row:2,
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'fraccionArancelaria',
      labelNombre: 'Fracción arancelaria',
      campo: 'fraccionArancelaria',
      clase: 'col-md-4',
      tipoInput: 'text',
      row:3,
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'cantidadAutorizada',
      labelNombre: 'Cantidad autorizada',
      campo: 'cantidadAutorizada',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'valorAutorizado',
      labelNombre: 'Valor autorizado',
      campo: 'valorAutorizado',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      row:3,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
    {
      id: 'nico',
      labelNombre: 'NICO',
      campo: 'nico',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: false,
      soloLectura: false,
      row:3,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
    {
      id: 'descripcionNico',
      labelNombre: ' Descripción NICO',
      campo: 'descripcionNico',
      clase: 'col-md-4',
      tipoInput: 'textarea',
      desactivado: false,
      soloLectura: false,
      row:3,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
    {
      id: 'acotacion',
      labelNombre: 'Acotación',
      campo: 'acotacion',
      clase: 'col-md-4',
      tipoInput: 'textarea',
      desactivado: false,
      soloLectura: false,
      row:3,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    },
   
    {
      id: 'permisoValidoDesde',
      labelNombre: 'Permiso válido desde',
      campo: 'permisoValidoDesde',
      clase: 'col-md-4',
      tipoInput: 'date',
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      habilitado: true
    },

  {
      id: 'permisoValidoHasta',
      labelNombre: 'Permiso válido hasta',
      campo: 'permisoValidoHasta',
      clase: 'col-md-4',
      tipoInput: 'date',
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
      habilitado: true
    },
  ]
  