/**
 * @constant PANTA_PASOS
 * @description Pasos del proceso para la gestión de permisos de petróleo.
 */
export const PANTA_PASOS = [
    {
      indice: 1,
      titulo: 'Capturar solicitud',
      activo: true,
      completado: true,
    },
    {
      indice: 2,
      titulo: 'Anexar requisitos',
      activo: false,
      completado: false,
    },
    {
      indice: 3,
      titulo: 'Firmar solicitud',
      activo: false,
      completado: false,
    },
  ];

/**
 * @constant INFORMACION_DE_LA_OBRA_ARTE
 * @description Información detallada de la obra de arte relacionada con el permiso.
 */
export const INFORMACION_DE_LA_OBRA_ARTE = [
    {
      id: 'folioTramite',
      labelNombre: 'Folio trámite',
      campo: 'folioTramite',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: '1300254125004512541254',
      marginTop: 0,
    },
    
    {
      id: 'tipoSolicitud',
      labelNombre: 'Tipo de solicitud',
      campo: 'tipoSolicitud',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: 'inicial',
      marginTop: 0,
    },
    {
      id: 'regimen',
      labelNombre: 'Régimen',
      campo: 'regimen',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: 'Temporerales',
      marginTop: 0,
    },
    {
      id: 'clasificacionRegimen',
      labelNombre: 'Clasificación del régimen',
      campo: 'clasificacionRegimen',
      clase: 'col-md-4',
      tipoInput: 'textarea',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: 'Declaración de importación',
      marginBottom: 0,
    },
    {
      id: 'periodoVigencia',
      labelNombre: 'Periodo de vigencia',
      campo: 'periodoVigencia',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: 'Corto plazo',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'unidadMedida',
      labelNombre: 'Unidad de medida',
      campo: 'unidadMedida',
      clase: 'col-md-4',
      tipoInput: 'text',
     desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: 'Litros',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'fraccionArancelaria',
      labelNombre: 'Fracción arancelaria',
      campo: 'fraccionArancelaria',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: '27111901',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'cantidadAutorizada',
      labelNombre: 'Cantidad autorizada',
      campo: 'cantidadAutorizada',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: '852,741,963.58',
      marginTop: 0,
      marginBottom: 0,
    },
    {
      id: 'valorAutorizado',
      labelNombre: 'Valor autorizado',
      campo: 'valorAutorizado',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: '1234567892.58',
      marginTop: 0,
    },
    {
      id: 'nico',
      labelNombre: 'NICO',
      campo: 'nico',
      clase: 'col-md-4',
      tipoInput: 'text',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: '0000000000',
      marginTop: 0,
    },
    {
      id: 'descripcionNico',
      labelNombre: 'Descripción NICO',
      campo: 'descripcionNico',
      clase: 'col-md-4',
      tipoInput: 'textarea',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: 'Descripción del NICO',
      marginTop: 0,
    },
    {
      id: 'acotacion',
      labelNombre: 'Acotación',
      campo: 'acotacion',
      clase: 'col-md-4',
      tipoInput: 'textarea',
      desactivado: true,
      soloLectura: true,
      marcadorDePosicion: '',
      valorPredeterminado: 'Declaración de importación',
      marginTop: 0,
    },
    {
      id: 'permisoValidoDesde',
      labelNombre: 'Permiso válido desde',
      campo: 'permisoValidoDesde',
      clase: 'col-md-4',
      tipoInput: 'date',
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '05/10/2023',
      marginTop: 0,
      habilitado: true,
    },
    {
      id: 'permisoValidoHasta',
      labelNombre: 'Permiso válido hasta',
      campo: 'permisoValidoHasta',
      clase: 'col-md-4',
      tipoInput: 'date',
      desactivado: false,
      soloLectura: false,
      marcadorDePosicion: '',
      valorPredeterminado: '25/10/2025',
      marginTop: 0,
      habilitado: true,
    },
  ];

/**
 * @constant AVISO_PRIVACIDAD
 * @description Aviso de privacidad relacionado con las notificaciones del trámite.
 */
export const AVISO_PRIVACIDAD = 
      'Acepto expresamente que todas las notificaciones relacionadas con la presente solicitud y/o el permiso que, en su caso, deriven de la misma, se realizarán a través del correo electrónico registrado en la Ventanilla Digital Mexicana de Comercio Exterior (V U CE M) en relación con esta solicitud, y/o por medio de las cuentas de correo electrónico que señale como medios de comunicación oficial con la SEN ER en relación con este trámite; en el entendido de que dichas notificaciones, con independencia de lo establecido en cualquier otra regla, siempre surtirán sus efectos al día siguiente de que hayan sido cargadas en V U CEM y notificadas a través de los correos electrónicos antes señalados Por lo que manifiesto, bajo protesta de decir verdad, que acepto que prevalezcan para esta solicitud y lo relacionado con la misma, las reglas de notificación descritas en el párrafo que antecede, y me comprometo a revisar continuamente los avisos que emita la VU CE M, así como las notificaciones recibidas en los correos electrónicos señalados como medios de comunicación oficial con la SEN ER, a fin de proceder con oportunidad conforme a derecho corresponda';

