export const PERSONA_FISICA_NACIONAL = [
  {
    labelNombre: 'CURP',
    campo: 'curp',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    tooltip: 'Clave Única de Registro de Población',
    validators: ['required', 'maxLength:18', 'minLength:18', 'pattern:curp'],
    placeholder: '',
  },
  {
    labelNombre: 'RFC',
    campo: 'rfc',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    tooltip: 'Regulación Federal de Contribuyentes',
    validators: ['required', 'maxLength:13', 'minLength:12', 'pattern:rfc'],
    placeholder: '',
  },
  {
    labelNombre: '',
    campo: '',
    class: 'col-md-4',
    visibility: 'hidden',
    tipo_input: '',
    disabled: true,
    tooltip: '',
    validators: [''],
    placeholder: '',
  },
  {
    labelNombre: 'Nombre(s)',
    campo: 'nombreRazonSocial',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required'],
    placeholder: '',
  },
  {
    labelNombre: 'Primer apellido',
    campo: 'primerApellido',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required'],
    placeholder: '',
  },
  {
    labelNombre: 'Segundo apellido',
    campo: 'segundoApellido',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required'],
    placeholder: '',
  },
  {
    labelNombre: 'Actividad económica preponderante',
    campo: 'actEconomica',
    class: 'col-md-8',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:120'],
    placeholder: '',
  },
  {
    labelNombre: 'Correo electrónico',
    campo: 'correo',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:30', 'pattern:email'],
    placeholder: '',
  },
];

export const DOMICILIO_FISCAL_PERSONA_MORAL_O_FISICA_NACIONAL = [
  {
    labelNombre: 'País',
    campo: 'pais',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:120'],
    placeholder: '',
  },
  {
    labelNombre: 'Código postal',
    campo: 'codigoPostal',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:10'],
    placeholder: '',
  },
  {
    labelNombre: 'Estado',
    campo: 'entidadFederativa',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:50'],
    placeholder: '',
  },
  {
    labelNombre: 'Municipio o alcaldía',
    campo: 'municipio',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:120'],
    placeholder: '',
  },
  {
    labelNombre: 'Localidad',
    campo: 'localidad',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:68'],
    placeholder: '',
  },
  {
    labelNombre: 'Colonia',
    campo: 'colonia',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:68'],
    placeholder: '',
  },
  {
    labelNombre: 'Calle',
    campo: 'calle',
    class: 'col-md-8',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:68'],
    placeholder: '',
  },
  {
    labelNombre: 'Número exterior',
    campo: 'nExt',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:10'],
    placeholder: '',
  },
  {
    labelNombre: 'Número interior',
    campo: 'nInt',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['maxLength:15'],
    placeholder: '',
  },
  {
    labelNombre: 'Lada',
    campo: 'lada',
    class: 'col-md-1',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:15'],
    placeholder: '',
  },
  {
    labelNombre: 'Teléfono',
    campo: 'telefono',
    class: 'col-md-3',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:15'],
    placeholder: '',
  },
];

export const PERSONA_MORAL_NACIONAL = [
  {
    labelNombre: 'RFC:',
    campo: 'rfc',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    tooltip: 'Regulación Federal de Contribuyentes',
    validators: ['required', 'maxLength:13', 'minLength:12', 'pattern:rfc'],
    placeholder: '',
  },
  {
    labelNombre: 'Denominación o razón social:',
    campo: 'nombreRazonSocial',
    class: 'col-md-8',
    tipo_input: 'text',
    disabled: true,
    validators: ['required'],
    placeholder: '',
  },
  {
    labelNombre: 'Actividad económica preponderante:',
    campo: 'actEconomica',
    class: 'col-md-12',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:120'],
    placeholder: '',
  },
  {
    labelNombre: 'Correo electrónico:',
    campo: 'correo',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:30', 'pattern:email'],
    placeholder: '',
  },
];

export const PERSONA_FISICA_EXTRANJERO = [
  {
    labelNombre: 'Nombre(s)',
    campo: 'nombreRazonSocial',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required'],
    placeholder: '',
  },
  {
    labelNombre: 'Primer apellido',
    campo: 'primerApellido',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required'],
    placeholder: '',
  },
  {
    labelNombre: 'Segundo apellido',
    campo: 'segundoApellido',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required'],
    placeholder: '',
  },
  {
    labelNombre: 'Número de identificación fiscal',
    campo: 'nIdentificacionFiscal',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:120'],
    placeholder: '',
  },
  {
    labelNombre: 'Número de seguro social',
    campo: 'nSeguroSocial',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:120'],
    placeholder: '',
  },
  {
    labelNombre: 'Correo electrónico',
    campo: 'correo',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:30', 'pattern:email'],
    placeholder: '',
  },
];

export const PERSONA_MORAL_EXTRANJERO = [
  {
    labelNombre: 'Nombre(s)',
    campo: 'nombreRazonSocial',
    class: 'col-md-8',
    tipo_input: 'text',
    disabled: true,
    validators: ['required'],
    placeholder: '',
  },
  {
    labelNombre: 'Correo electrónico',
    campo: 'correo',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:30', 'pattern:email'],
    placeholder: '',
  },
];


export const DOMICILIO_FISCAL_PERSONA_MORAL_O_FISICA_EXTRANJERA = [
  {
    labelNombre: 'País',
    campo: 'pais',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:120'],
    placeholder: '',
  },
  {
    labelNombre: 'Código postal',
    campo: 'codigoPostal',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:10'],
    placeholder: '',
  },
  {
    labelNombre: 'Estado',
    campo: 'entidadFederativa',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:50'],
    placeholder: '',
  },
  {
    labelNombre: 'Calle',
    campo: 'calle',
    class: 'col-md-8',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:68'],
    placeholder: '',
  },
  {
    labelNombre: 'Número y/o letra exterior',
    campo: 'nExt',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['required', 'maxLength:10'],
    placeholder: '',
  },
  {
    labelNombre: 'Número interior',
    campo: 'nInt',
    class: 'col-md-4',
    tipo_input: 'text',
    disabled: true,
    validators: ['maxLength:15'],
    placeholder: '',
  },
];
