export const MERCANCIAS = [
    {
      labelNombre: 'Aduana por la que ingresará la mercancía',
      campo: 'aduana',
      class: 'col-md-8',
      tipo_input: 'select-catalogos',
      disabled: false,
      validators: ['required'],
      placeholder: '---Seleccionia---',
    },
    {
      labelNombre: 'Organisamo publico',
      campo: 'organisamoPublico',
      class: 'col-md-4',
      tipo_input: 'checkbox',
      disabled: false,
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'Fin al cual se destinara la mercancia',
      campo: 'finAlDestinara',
      class: 'col-md-12',
      tipo_input: 'textarea',
      disabled: false,
      tooltip: '',
      validators: ['required'],
      placeholder: '',
    }
  ];

  export const PRODUCTOS = [
    {
      labelNombre: 'Tipo de mercancia',
      campo: 'tipoDeMercancia',
      class: 'col-md-4',
      tipo_input: 'text',
      disabled: false,
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'Condicion de la mercancia',
      campo: 'condicionDeLaMercancia',
      class: 'col-md-8',
      tipo_input: 'text',
      disabled: true,
      validators: [''],
      placeholder: '',
    },
    {
      labelNombre: 'Cantidad',
      campo: 'cantidad',
      class: 'col-md-8',
      tipo_input: 'text',
      disabled: false,
      tooltip: '',
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'Unidad de medida',
      campo: 'unidadDeMedida',
      class: 'col-md-4',
      tipo_input: 'select-catalogos',
      disabled: false,
      tooltip: '',
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'En su caso (maquinaria y equipo onsoleto)',
      campo: 'enSuCaso',
      class: 'col-md-12',
      tipo_input: '',
      disabled: false,
      tooltip: '',
      validators: [''],
      placeholder: '',
    },
    {
        labelNombre: 'Marca',
        campo: 'marca',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: false,
        tooltip: '',
        validators: [''],
        placeholder: '',
      },
      {
        labelNombre: 'Ano de importacion temporal',
        campo: 'anoDeImportacionTemporal',
        class: 'col-md-4',
        tipo_input: 'select-catalogos',
        disabled: false,
        tooltip: '',
        validators: [''],
        placeholder: '',
      },
      {
        labelNombre: 'Modelo',
        campo: 'modelo',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: false,
        tooltip: '',
        validators: [''],
        placeholder: '',
      },
      {
        labelNombre: 'Numero de serie',
        campo: 'numeroDeSerie',
        class: 'col-md-8',
        tipo_input: 'text',
        disabled: false,
        tooltip: '',
        validators: [''],
        placeholder: '',
      }
  ];

  export const DATOS_DEL_DONANTE = [
    {
      labelNombre: 'RFC',
      campo: 'rfc',
      class: 'col-md-4',
      tipo_input: 'text',
      disabled: false,
      validators: ['required'],
      placeholder: '',
      tooltip: ''
    },
    {
      labelNombre: 'Numero de programa Immex',
      campo: 'programaImmex',
      class: 'col-md-8',
      tipo_input: 'text',
      disabled: true,
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'Nombre / Razon Social',
      campo: 'nombreRazonSocial',
      class: 'col-md-8',
      tipo_input: 'text',
      disabled: false,
      tooltip: '',
      validators: ['required'],
      placeholder: '',
    }
  ];

  export const DOMICILIO_FISCAL = [
    {
      labelNombre: 'Pais',
      campo: 'pais',
      class: 'col-md-4',
      tipo_input: 'text',
      disabled: true,
      validators: ['required'],
      placeholder: '',
      tooltip: ''
    },
    {
      labelNombre: 'C.P o zona postal',
      campo: 'zonaPostal',
      class: 'col-md-4',
      tipo_input: 'text',
      disabled: true,
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'Estado',
      campo: 'estado',
      class: 'col-md-4',
      tipo_input: 'text',
      disabled: true,
      tooltip: '',
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'Colonia',
      campo: 'colonia',
      class: 'col-md-4',
      tipo_input: 'text',
      disabled: true,
      tooltip: '',
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'Calle',
      campo: 'calle',
      class: 'col-md-8',
      tipo_input: 'text',
      disabled: true,
      tooltip: '',
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'Numero y/o letra exterior',
      campo: 'numeroExterior',
      class: 'col-md-4',
      tipo_input: 'text',
      disabled: true,
      tooltip: '',
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'Numero y/o letra interior',
      campo: 'numeroInterior',
      class: 'col-md-4',
      tipo_input: 'text',
      disabled: true,
      tooltip: '',
      validators: ['required'],
      placeholder: '',
    },
    {
      labelNombre: 'Correo electronico',
      campo: 'correoElectronico',
      class: 'col-md-8',
      tipo_input: 'text',
      disabled: true,
      tooltip: '',
      validators: [''],
      placeholder: '',
    },
    {
      labelNombre: 'Telefono',
      campo: 'telephono',
      class: 'col-md-4',
      tipo_input: 'text',
      disabled: true,
      tooltip: '',
      validators: [''],
      placeholder: '',
    },
    {
      labelNombre: 'Correo electronico (opcional)',
      campo: 'correoElectronicoOpcional',
      class: 'col-md-8',
      tipo_input: 'text',
      disabled: false,
      tooltip: '',
      validators: [''],
      placeholder: '',
    },
    {
      labelNombre: 'Telefono (opcional)',
      campo: 'telephonoOpcional',
      class: 'col-md-4',
      tipo_input: 'text',
      disabled: false,
      tooltip: '',
      validators: [''],
      placeholder: '',
    }
  ];

  export const DATOS_ALERT = {
    message: `<p>Debes capturar la descripción de la mercancía en los mismos términos de la carta de donación</p>`,
  };