/**
 * Constantes para el manejo de los pasos del wizard de cupos
 *
 */
export const CUPOS_PASOS = [
  {
    indice: 1,
    titulo: 'Capturar solicitud',
    activo: true,
    completado: true,
  },
  {
    indice: 2,
    titulo: 'Firmar solicitud',
    activo: false,
    completado: false,
  },
];

export const DATOS_GENERALES_DEL_SOLICITANTE = [
  {
    id: 'rfc',
    labelNombre: 'RFC',
    campo: 'rfc',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: 'AFC000526BJ2',
    marginTop: 0,
  },
  {
    id: 'denominacion',
    labelNombre: 'Denominación o razón social',
    campo: 'denominacion',
    clase: 'col-md-8',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado:
      'CONSORCIO DISTRIBUIDOR DE MEDICINAS Y MEDICAMENTOS GREY SA DE CV',
    marginTop: 0,
  },
  {
    id: 'actividad',
    labelNombre: 'Actividad económica preponderante',
    campo: 'actividad',
    clase: 'col-md-12',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado:
      'Otros servicios de almacenamiento general sin instalaciones especializadas',
    marginTop: 0,
  },
  {
    id: 'correoElectronico',
    labelNombre: 'Correo electrónico',
    campo: 'correoElectronico',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: 'vucem2.5@hotmail.com',
    marginTop: 0,
  },
];

export const DOMICILIO_FISCAL_DEL_SOLICITANTE = [
  {
    id: 'pais',
    labelNombre: 'País',
    campo: 'pais',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: 'ESTADOS UNIDOS MEXICANOS',
    marginTop: 0,
  },
  {
    id: 'codigoPostal',
    labelNombre: 'Código postal',
    campo: 'codigoPostal',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '31109',
    marginTop: 0,
  },
  {
    id: 'estado',
    labelNombre: 'Estado',
    campo: 'estado',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: 'CHIHUAHUA',
    marginTop: 0,
  },
  {
    id: 'municipio',
    labelNombre: 'Municipio o alcaldía',
    campo: 'municipio',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: 'CHIHUAHUA',
    marginTop: 0,
  },
  {
    id: 'localidad',
    labelNombre: 'Localidad',
    campo: 'localidad',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: 'CHIHUAHUA',
    marginTop: 0,
  },
  {
    id: 'colonia',
    labelNombre: 'Colonia',
    campo: 'colonia',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: 'COMPLEJO INDUSTRIAL CHIHUAHUA',
    marginTop: 0,
  },
  {
    id: 'calle',
    labelNombre: 'Calle',
    campo: 'calle',
    clase: 'col-md-8',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: 'PASEO 4 MILPAS',
    marginTop: 0,
  },
  {
    id: 'numeroExterior',
    labelNombre: 'Número exterior',
    campo: 'numeroExterior',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '102',
    marginTop: 0,
  },
  {
    id: 'numeroInterior',
    labelNombre: 'Número interior',
    campo: 'numeroInterior',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'lada',
    labelNombre: 'Lada',
    campo: 'lada',
    clase: 'col-md-1',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'telephono',
    labelNombre: 'Teléfono',
    campo: 'telephono',
    clase: 'col-md-3',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
];

export const CONSULTAR_CUPO = [
  {
    id: 'tratado',
    labelNombre: 'Tratado 0 acuerado',
    campo: 'tratado',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '1',
    marginTop: 0,
    opciones: [{ id: 1, descripcion: 'TMEC' }],
  },
  {
    id: 'clasificacion',
    labelNombre: 'Clasificación del regimen',
    campo: 'clasificacion',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: '',
    labelNombre: '',
    campo: '',
    clase: 'col-md-4',
    tipoInput: '',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'pais',
    labelNombre: 'País destino/origen',
    campo: 'pais',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'fraccionArancelaria',
    labelNombre: 'Fraccion arancelaria',
    campo: 'fraccionArancelaria',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
];

export const DESCRIPCION_DEL_CUPO = [
  {
    id: 'fraccionArancelaria',
    labelNombre: 'Fraccion arancelaria',
    campo: 'fraccionArancelaria',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'descripcionProducto',
    labelNombre: 'Descripción del producto',
    campo: 'descripcionProducto',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'tratadoBloque',
    labelNombre: 'Tratado o bloque',
    campo: 'tratadoBloque',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'clasificacionSubproducto',
    labelNombre: 'Clasificación del subproducto',
    campo: 'clasificacionSubproducto',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'mecanismo',
    labelNombre: 'Mecanismo de asignación',
    campo: 'mecanismo',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'categoria',
    labelNombre: 'Categoría textil',
    campo: 'categoria',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'clasificacionRegimen',
    labelNombre: 'Clasificación de régimen',
    campo: 'clasificacionRegimen',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'descripcionCategoria',
    labelNombre: 'Descripción de la categoría textil',
    campo: 'descripcionCategoria',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'paisDestino',
    labelNombre: 'País destino/origen',
    campo: 'paisDestino',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'unidadDeMedida',
    labelNombre: 'Unidad de medida categoría textil',
    campo: 'unidadDeMedida',
    clase: 'col-md-6',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'factor',
    labelNombre: 'Factor de conversión de la categoría textil',
    campo: 'factor',
    clase: 'col-md-6',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'fechaDeInicio',
    labelNombre: 'Fecha de inicio de vigencia',
    campo: 'fechaDeInicio',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'fechaDeFin',
    labelNombre: 'Fecha de fin de vigencia',
    campo: 'fechaDeFin',
    clase: 'col-md-4',
    tipoInput: 'text',
    desactivado: true,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
];

export const REPRESENTACION_FEDERAL = [
  {
    id: 'estado',
    labelNombre: 'Estado',
    campo: 'estado',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'representacionFederal',
    labelNombre: 'Representación federal',
    campo: 'representacionFederal',
    clase: 'col-md-4',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    marcadorDePosicion: 'Selecciona un valor',
    valorPredeterminado: '',
    marginTop: 0,
  },
];
