services:
#----------------------------------------------------------------
  modulefederation-agricultura-microfront:
    image: modulefederation-agricultura-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/agricultura/Dockerfile
    container_name: modulefederation-agricultura-microfront
    restart: on-failure
    expose:
      - '4204'
    ports:
      - "4204:80"
    networks:
      - modulefederation-network
#----------------------------------------------------------------
networks:
  modulefederation-network:
