services:
#----------------------------------------------------------------
  modulefederation-funcionario-microfront:
    image: modulefederation-funcionario-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/funcionario/Dockerfile.dev
    container_name: modulefederation-funcionario-microfront
    restart: on-failure
    expose:
      - '4210'
    ports:
      - "4210:80"
    networks:
      - modulefederation-network
#----------------------------------------------------------------
networks:
  modulefederation-network:
