services:
#----------------------------------------------------------------
  modulefederation-amecafe-microfront:
    image: modulefederation-amecafe-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/amecafe/Dockerfile
    container_name: modulefederation-amecafe-microfront
    restart: on-failure
    expose:
      - '4212'
    ports:
      - "4212:80"
    networks:
      - modulefederation-network
#----------------------------------------------------------------
networks:
  modulefederation-network:
