services:
#----------------------------------------------------------------
  modulefederation-agriculture-microfront:
    image: ghcr.io/vucem30/dockerized-modulefederation-agriculture-microfront:latest
    build: 
      context: ./../
      dockerfile: apps/agriculture/Dockerfile.dev
    container_name: modulefederation-agriculture-microfront
    restart: on-failure
    expose:
      - '4204'
    ports:
      - "4204:80"
    networks:
      - modulefederation-network
#----------------------------------------------------------------
networks:
  modulefederation-network:
