services:
#----------------------------------------------------------------
  modulefederation-dashboard:
    image: modulefederation-dashboard:1.0.0
    build: 
      context: ./../
      dockerfile: apps/dashboard/Dockerfile
    container_name: modulefederation-dashboard
    restart: on-failure
    expose:
      - '4200'
    ports:
      - "4200:80"
    networks:
      - modulefederation-network

#----------------------------------------------------------------
  modulefederation-login-microfront:
    image: modulefederation-login-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/login/Dockerfile
    container_name: modulefederation-login-microfront
    restart: on-failure
    expose:
      - '4201'
    ports:
      - "4201:80"
    depends_on:
      - modulefederation-dashboard
    networks:
      - modulefederation-network

#----------------------------------------------------------------
  modulefederation-aga-microfront:
    image: modulefederation-aga-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/aga/Dockerfile
    container_name: modulefederation-aga-microfront
    restart: on-failure
    expose:
      - '4202'
    ports:
      - "4202:80"
    depends_on:
      - modulefederation-login-microfront
    networks:
      - modulefederation-network

#----------------------------------------------------------------
  modulefederation-agriculture-microfront:
    image: modulefederation-agriculture-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/agriculture/Dockerfile
    container_name: modulefederation-agriculture-microfront
    restart: on-failure
    expose:
      - '4204'
    ports:
      - "4204:80"
    networks:
      - modulefederation-network

#----------------------------------------------------------------
  modulefederation-se-microfront:
    image: modulefederation-se-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/se/Dockerfile
    container_name: modulefederation-se-microfront
    restart: on-failure
    expose:
      - '4205'
    ports:
      - "4205:80"
    networks:
      - modulefederation-network

#----------------------------------------------------------------
  modulefederation-semarnat-microfront:
    image: modulefederation-semarnat-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/semarnat/Dockerfile
    container_name: modulefederation-semarnat-microfront
    restart: on-failure
    expose:
      - '4206'
    ports:
      - "4206:80"
    networks:
      - modulefederation-network

#----------------------------------------------------------------
  modulefederation-agace-microfront:
    image: modulefederation-agace-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/agace/Dockerfile
    container_name: modulefederation-agace-microfront
    restart: on-failure
    expose:
      - '4209'
    ports:
      - "4209:80"
    networks:
      - modulefederation-network

#----------------------------------------------------------------
  modulefederation-funcionario-microfront:
    image: modulefederation-funcionario-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/funcionario/Dockerfile
    container_name: modulefederation-funcionario-microfront
    restart: on-failure
    expose:
      - '4210'
    ports:
      - "4210:80"
    networks:
      - modulefederation-network

#----------------------------------------------------------------
  modulefederation-cofepris-microfront:
    image: modulefederation-cofepris-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/cofepris/Dockerfile
    container_name: modulefederation-cofepris-microfront
    restart: on-failure
    expose:
      - '4211'
    ports:
      - "4211:80"
    networks:
      - modulefederation-network

#----------------------------------------------------------------
  modulefederation-amecafe-microfront:
    image: modulefederation-amecafe-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/amecafe/Dockerfile
    container_name: modulefederation-amecafe-microfront
    restart: on-failure
    expose:
      - '4212'
    ports:
      - "4212:80"
    networks:
      - modulefederation-network

#----------------------------------------------------------------
networks:
  modulefederation-network:
