services:
#----------------------------------------------------------------
  modulefederation-se-microfront:
    image: modulefederation-se-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/se/Dockerfile.dev
    container_name: modulefederation-se-microfront
    restart: on-failure
    expose:
      - '4205'
    ports:
      - "4205:80"
    networks:
      - modulefederation-network
#----------------------------------------------------------------
networks:
  modulefederation-network:
