services:
#----------------------------------------------------------------
  modulefederation-libs:
    image: modulefederation-libs:1.0.0
    build: 
      context: ./../
      dockerfile: libs/shared/Dockerfile
    container_name: modulefederation-libs
    restart: on-failure
    expose:
      - '4203'
    ports:
      - "4203:80"
    networks:
      - modulefederation-network
#----------------------------------------------------------------
networks:
  modulefederation-network:
