services:
#----------------------------------------------------------------
  modulefederation-semarnat-microfront:
    image: modulefederation-semarnat-microfront:1.0.0
    build: 
      context: ./../
      dockerfile: apps/semarnat/Dockerfile.dev
    container_name: modulefederation-semarnat-microfront
    restart: on-failure
    expose:
      - '4206'
    ports:
      - "4206:80"
    networks:
      - modulefederation-network
#----------------------------------------------------------------
networks:
  modulefederation-network:
