export const PASOS = [
    {
        indice: 1,
        titulo: 'Capturar solicitud',
        activo: true,
        completado: true,
    },
    {
        indice: 2,
        titulo: 'Requisitos necesarios',
        activo: false,
        completado: false,
    },
    {
        indice: 3,
        titulo: 'Anexar necesarios',
        activo: false,
        completado: false,
    },
    {
        indice: 4,
        titulo: 'Firmar solicitud',
        activo: false,
        completado: false,
    },
];
export const FITOSANITARIO_SOLICITANTE_FISICA_NACIONAL = [
    {
        labelNombre: 'Registro federal de contribuyentes:',
        campo: 'rfc',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        tooltip: 'Registro federal de contribuyentes:',
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Denominacion o razon social:',
        campo: 'nombreRazonSocial',
        class: 'col-md-8',
        tipo_input: 'text',
        disabled: true,
        tooltip: 'Denominacion o razon social',
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Actividad económica preponderante:',
        campo: 'actEconomica',
        class: 'col-md-12',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Correo electronic',
        campo: 'correo',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    }
];
export const FITOSANITARIO_PERSONA_MORAL_O_FISICA_NACIONAL = [
    {
        labelNombre: 'País',
        campo: 'pais',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required', 'maxLength:120'],
        placeholder: '',
    },
    {
        labelNombre: 'Código Postal',
        campo: 'codigoPostal',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required', 'maxLength:10'],
        placeholder: '',
    },
    {
        labelNombre: 'Estado',
        campo: 'entidadFederativa',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required', 'maxLength:50'],
        placeholder: '',
    },
    {
        labelNombre: 'Municipio o alcaldía',
        campo: 'municipio',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required', 'maxLength:120'],
        placeholder: '',
    },
    {
        labelNombre: 'Localidad',
        campo: 'localidad',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required', 'maxLength:68'],
        placeholder: '',
    },
    {
        labelNombre: 'Colonia',
        campo: 'colonia',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required', 'maxLength:68'],
        placeholder: '',
    },
    {
        labelNombre: 'Calle',
        campo: 'calle',
        class: 'col-md-8',
        tipo_input: 'text',
        disabled: true,
        validators: ['required', 'maxLength:68'],
        placeholder: '',
    },
    {
        labelNombre: 'Número exterior',
        campo: 'nExt',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required', 'maxLength:10'],
        placeholder: '',
    },
    {
        labelNombre: 'Número interior',
        campo: 'nInt',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['maxLength:15'],
        placeholder: '',
    },
    {
        labelNombre: 'Lada',
        campo: 'lada',
        class: 'col-md-1',
        tipo_input: 'text',
        disabled: true,
        validators: ['required', 'maxLength:15'],
        placeholder: '',
    },
    {
        labelNombre: 'Teléfono',
        campo: 'telefono',
        class: 'col-md-3',
        tipo_input: 'text',
        disabled: true,
        validators: ['required', 'maxLength:15'],
        placeholder: '',
    },
];
export const INSTRUCCION_DOBLE_CLIC = 'Al dar doble clic en el registro seleccionado creará una nueva solicitud con los mismos datos de la solicitud elegida'