# Dockerfile for CRT app
FROM node:22-slim AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./


# Install pnpm
RUN npm install -g pnpm && \
    pnpm install --frozen-lockfile

# Copy source code
COPY apps ./apps
COPY libs ./libs

# Build the app
ARG NODE_ENV=production
ARG APP_NAME
RUN npx nx build $APP_NAME --configuration=$NODE_ENV --base-href=/$APP_NAME/ --skip-nx-cache

# Inject version
ARG VERSION="unknown"
ENV VERSION=$VERSION
RUN node script/inject-version.js $APP_NAME

# Stage 2: Serve with Nginx
FROM nginx:alpine-slim

# Remove default config
RUN rm -rf /etc/nginx/conf.d/default.conf

# Copy custom nginx.conf from build context
COPY nginx.conf /etc/nginx/conf.d/crt.conf

# Copy built assets from builder
COPY --from=builder /app/dist/apps/${APP_NAME} /usr/share/nginx/html

# Expose port
EXPOSE 80

# Health check
HEALTHCHECK --interval=10s --timeout=3s --start-period=15s --retries=3 \
  CMD curl -f http://localhost/$APP_NAME/ || exit 1

# Run nginx
CMD ["nginx", "-g", "daemon off;"]
