export interface ScianDatos {
    clave: string,
    descripcion: string,
}


export interface MercanciasDatos {
  clasificacion: string,
  especificar: string,
  dci: string,
  denominacion: string,
  numero: string,
  fraccion: string,
  descripcionDeLa: string,
  tipoDeProducto: string,
  formaFarmaceutica: string,
  umt: string,
  umc: string,
  numeroCas: string,
  cantidad: string,
  kg: string,
  paisDeDestino: string,
  paisDeOrigen: string,
  paisDeProcedencia: string,
  uso: string,
  detalle: string,
  cantidadUmc: string,
  dePiezas: string,
  descripcionDePiezas: string,
  numeroDeReg: string,
  presentacion: string,
}

export interface Fabricante {
  nombre: string,
  rfc: string,
  curp: string,
  telefono: string,
  correoElectronico: string,
  calle: string,
  numeroExterior: string,
  numeroInterior: string,
  pais: string,
  colonia: string,
  municipio: string,
  localidad: string,
  entidadFederativa: string,
  estado: string,
  cp: string,
}

export interface Otros {
  tercero: string,
  nombre: string,
  rfc: string,
  curp: string,
  telefono: string,
  correoElectronico: string,
  calle: string,
  numeroExterior: string,
  numeroInterior: string,
  pais: string,
  colonia: string,
  municipio: string,
  localidad: string,
  entidadFederativa: string,
  estado: string,
  cp: string,
}