import { RowTypeFormInput } from "../../../shared/models/row-type-form-input.model"

export const TRANSPORTE_FERROVARIO = [
    {
    id: 'senaleSiCuenta',
    labelNombre: 'Señale si cuenta con al menos 2 años de experiencia en la prestación de servicios de transporte de mercancías por ferrocarril, anteriores a su solicitud.',
    campo: 'senaleSiCuenta',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'indiqueLaFecha',
    labelNombre: 'Indique la fecha en que inició la prestación de servicios de transporte de mercancías por ferrocarril.',
    campo: 'indiqueLaFecha',
    clase: 'col-md-12',
    tipoInput: 'label-only',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'fechaDeInicio',
    labelNombre: 'Fecha de Inicio de Servicios de Transporte',
    campo: 'fechaDeInicio',
    clase: 'col-md-6',
    tipoInput: 'date',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    habilitado: true,
  },
  {
    id: 'senaleSiSuSolicitud',
    labelNombre: 'Señale si su solicitud es sobre la red completa de ferrocarril o sobre un tramo',
    campo: 'senaleSiSuSolicitud',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Red Completa',
        value: 1,
      },
      {
        label: 'Tramo de Red',
        value: 2,
      },
    ]
  },
  {
    id: 'customSection1_transporte',
    labelNombre: '',
    campo: '',
    clase: 'col-md-4',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    templateKey: 'customSection1',
  },
  {
    id: 'indiqueSiCuentaCarga',
    labelNombre: 'Indique si cuenta con la concesión o el permiso vigente, expedido por la SCT para prestar el servicio de transporte ferroviario de carga.',
    campo: 'indiqueSiCuentaCarga',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'customSection2',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 5,
    templateKey: 'customSection2',
  },
  {
    id: 'senaleSiLaFechaServicio',
    labelNombre: 'Señale si a la fecha de presentación de su solicitud cuenta con unidades propias, arrendadas, en comodato u otra figura jurídica con la que acredite la posesión de las mismas(equipo tractivo), que utiliza para la prestación del servicio.',
    campo: 'senaleSiLaFechaServicio',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'customSection3',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 5,
    templateKey: 'customSection3',
  },
  {
    id: 'manifiesteSiCumple',
    labelNombre: 'Manifieste si cumple con los estándares mínimos en materia de seguridad establecidos en el formato denominado "Perfil del Transportista Ferroviario"',
    campo: 'manifiesteSiCumple',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
]

export const LISTADO_DE_SOCIO_COMERCIAL_CERTIFICADO = [
    {
    id: 'conLaFinalidad',
    labelNombre: 'Con la finalidad de crear cadenas de suministros más seguras, se establecerá un listado con las empresas que hayan obtenido la certificación como Socio Comercial, misma que se publicará en el Portal del SAT que incluirá los datos generales que la empresa autorice, así como el estatus de su certificación, mismas que podrán ser consultadas por las empresas que hayan obtenido su inscripción en el Registro de certificación de empresas.*',
    campo: 'conLaFinalidad',
    clase: 'col-md-12',
    tipoInput: 'label-only',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
    {
    id: 'rfc',
    labelNombre: 'RFC',
    campo: 'rfc',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'nombreRazonSocial',
    labelNombre: 'Nombre o Razón Social',
    campo: 'nombreRazonSocial',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'direccionFiscal',
    labelNombre: 'Dirección Fiscal',
    campo: 'direccionFiscal',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'paginaElectronica',
    labelNombre: 'Página Electrónica',
    campo: 'paginaElectronica',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'customSection4',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    templateKey: 'customSection4',
  },
  {
    id: 'correoElectronico',
    labelNombre: 'Correo Electrónico de contacto',
    campo: 'correoElectronico',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'customSection5',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    templateKey: 'customSection5',
  },
  {
    id: 'telefono',
    labelNombre: 'Teléfono de contacto',
    campo: 'telefono',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'customSection6',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    templateKey: 'customSection6',
  }
]

export const INFORMACION_GENERAL = [
  {
    id: 'domicilioInstalacion',
    labelNombre: 'Domicilio de la Instalación',
    campo: 'domicilioInstalacion',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
  },
  {
    id: 'elObjetivoDeEstePerfil',
    labelNombre: 'El objetivo de este Perfil, es el de asegurar que la empresa concesionaria de transporte ferroviario, desarrolle e implemente prácticas y procesos de seguridad que aseguren su cadena de suministro mitigando el riesgo de contaminación en sus equipos tractivos y de arrastre (furgones, góndolas, tolvas, carros tanque, contenedores, chasises, remolques, plataformas etc., que no tienen tracción propia que circulan en las vías férreas y que utilizan para transportar mercancía en su interior y en contenedores) con productos ilícitos, así como de pérdida o robo de mercancía y/o cualquier otro factor que pueda vulnerar la seguridad de la cadena de suministro',
    campo: 'elObjetivoDeEstePerfil',
    clase: 'col-md-12',
    tipoInput: 'label-only',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'conformeLaRegla',
    labelNombre: 'Conforme a la regla 7.1.5. fracción III, inciso a) y al formato denominado Perfil del Transportista Ferroviario" establecido en el Anexo 1 de las RGCE declare los siguiente:*',
    campo: 'conformeLaRegla',
    clase: 'col-md-12',
    tipoInput: 'label-only',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'customSection1_info',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 5,
    templateKey: 'customSection1',
  },
  {
    id: 'enCasoDeContar',
    labelNombre: 'En caso de contar con certificaciones en programas de seguridad, indique lo siguiente*:',
    campo: 'enCasoDeContar',
    clase: 'col-md-12',
    tipoInput: 'label-only',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'customsTradePartnership',
    labelNombre: 'Customs-Trade Partnership Against Terrorism (C-TPAT)',
    campo: 'customsTradePartnership',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'customSection2_info',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 3,
    templateKey: 'customSection2',
  },
  {
    id: 'pip',
    labelNombre: 'Partners in Protection (PIP)',
    campo: 'pip',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'customSection3_info',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 3,
    templateKey: 'customSection3',
  },
  {
    id: 'oea',
    labelNombre: 'Operador Económico Autorizado de otros países (OEA)',
    campo: 'oea',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'customSection4_info',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 3,
    templateKey: 'customSection4',
  },
  {
    id: 'otosProgramas',
    labelNombre: 'Otros Programas de Seguridad en la Cadena de Suministros',
    campo: 'otosProgramas',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'customSection5_info',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 3,
    templateKey: 'customSection5',
  },
  {
    id: 'indiqueSiCuentaOtros',
    labelNombre: 'Indique si cuenta con certificaciones que consideren que impactan en el proceso de su cadena de suministros, por ejemplo: ISO 9000; Procesos Logísticos Confiables, entre otros*',
    campo: 'indiqueSiCuentaOtros',
    clase: 'col-md-12',
    tipoInput: 'label-only',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: 'customSection6_info',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 3,
    templateKey: 'customSection6',
  },
]

export const TEMPLATE_3_ARRAY: RowTypeFormInput[] = [
  {
    id: 'unidadesPropias',
    label: 'Unidades Propias',
    tipoInput: 'text',
    formControlName: 'unidadesPropias',
    required: false,
  },
  {
    id: 'unidadesArrendadas',
    label: 'Unidades Arrendadas',
    tipoInput: 'text',
    formControlName: 'unidadesArrendadas',
    required: false,
  },
]

export const TEMPLATE_1_ARRAY: RowTypeFormInput[] = [
  {
    id: 'antiguedad',
    label: 'Antigüedad de la instalación (años de operación)',
    tipoInput: 'number',
    formControlName: 'antiguedad',
    required: false,
    labelColClase: 'col-md-6'
  },
  {
    id: 'actividadPreponderante',
    label: 'Actividad preponderante',
    tipoInput: 'number',
    formControlName: 'actividadPreponderante',
    required: false,
    labelColClase: 'col-md-6'
  },
  {
    id: 'tipoDeServicio',
    label: 'Tipo de servicio (Carga General/Especializada)	',
    tipoInput: 'number',
    formControlName: 'tipoDeServicio',
    required: false,
    labelColClase: 'col-md-6'
  },
  {
    id: 'noDeEmbarquesEXP',
    label: 'No. de embarques promedio mensual (EXP)',
    tipoInput: 'number',
    formControlName: 'noDeEmbarquesEXP',
    required: false,
    labelColClase: 'col-md-6'
  },
  {
    id: 'noDeEmbarquesIMP',
    label: 'No. de embarques promedio mensual (IMP)',
    tipoInput: 'number',
    formControlName: 'noDeEmbarquesIMP',
    required: false,
    labelColClase: 'col-md-6'
  },
  {
    id: 'numeroDeEmpleados',
    label: 'Número de empleados total de esta instalación',
    tipoInput: 'number',
    formControlName: 'numeroDeEmpleados',
    required: false,
    labelColClase: 'col-md-6'
  },
  {
    id: 'superficieDeLa',
    label: 'Superficie de la instalación (m2)	',
    tipoInput: 'number',
    formControlName: 'superficieDeLa',
    required: false,
    labelColClase: 'col-md-6'
  },
]

export const TEMPLATE_2_ARRAY: RowTypeFormInput[] = [
  {
    id: 'nivel',
    label: 'Nivel: certificado / certificado-validado',
    tipoInput: 'text',
    formControlName: 'nivel',
    required: false,
    labelColClase: 'col-md-6'
  },
  {
    id: 'ctpatAcc',
    label: 'CTPAT Account number',
    tipoInput: 'number',
    formControlName: 'ctpatAcc',
    required: false,
    labelColClase: 'col-md-6'
  },
  {
    id: 'tipoDeServicio',
    label: 'Tipo de servicio (Carga General/Especializada)	',
    tipoInput: 'number',
    formControlName: 'tipoDeServicio',
    required: false,
    labelColClase: 'col-md-6'
  },
  {
    id: 'mic',
    label: 'Manufacturer Identification Code (MID)',
    tipoInput: 'number',
    formControlName: 'mic',
    required: false,
    labelColClase: 'col-md-6'
  },
  {
    id: 'fechaDeUltima',
    label: 'Fecha de última visita de CTPAT recibida en la instalación',
    tipoInput: 'date',
    formControlName: 'fechaDeUltima',
    required: false,
    labelColClase: 'col-md-6'
  }
]

export const PIP_TEMPLATE_ARRAY: RowTypeFormInput[] = [
  {
    id: 'numeroRegistro',
    label: 'Número de registro',
    tipoInput: 'text',
    formControlName: 'numeroRegistro',
    required: false,
    inputColClase: 'col-md-4'
  }
]

export const OEA_TEMPLATE_ARRAY: RowTypeFormInput[] = [
  {
    id: 'nombreDelProgramaPais',
    label: 'Nombre del programa y país',
    tipoInput: 'text',
    formControlName: 'nombreDelProgramaPais',
    required: false,
    labelColClase: 'col-md-4'
  },
  {
    id: 'oea_numeroRegistro',
    label: 'Número de registro',
    tipoInput: 'text',
    formControlName: 'oea_numeroRegistro',
    required: false,
    labelColClase: 'col-md-4'
  }
]

export const OTROS_PROGRAMAS_TEMPLATE_ARRAY: RowTypeFormInput[] = [
  {
    id: 'nombreDelPrograma',
    label: 'Nombre del programa',
    tipoInput: 'text',
    formControlName: 'nombreDelPrograma',
    required: false
  },
  {
    id: 'otros_numeroRegistro',
    label: 'Número de registro',
    tipoInput: 'text',
    formControlName: 'otros_numeroRegistro',
    required: false
  },
  {
    id: 'vigencia',
    label: 'Vigencia',
    tipoInput: 'date',
    formControlName: 'vigencia',
    required: false
  }
]

export const ANALISIS_DE_RIESGO = [
  {
    id: 'indiqueSiElProcedimiento',
    labelNombre: 'Indique si el procedimiento le permita identificar otros riesgos o amenazas en la cadena de suministros, que se originen por cambios en las condiciones iniciales de la empresa.',
    campo: 'indiqueSiElProcedimiento',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleSiElProcedimiento',
    labelNombre: 'Señale si el procedimiento le permite identificar que las políticas, procedimientos y otros mecanismos de control y seguridad se estén cumpliendo.',
    campo: 'senaleSiElProcedimiento',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
   {
    id: 'senaleQuienesConforman',
    labelNombre: 'Señale quienes conforman el Comité de Seguridad de la compañía (Nombre y puesto)',
    campo: 'senaleQuienesConforman',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueCualesSon',
    labelNombre: 'Indique cuáles son las fuentes de información utilizadas para calificar los riesgos durante la fase de análisis.',
    campo: 'indiqueCualesSon',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'tipoDeServicio',
    labelNombre: 'Tipo de servicio: Tránsito interno/internacional',
    campo: 'tipoDeServicio',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const POLITICAS_DE_SEGURIDAD = [
  {
    id: 'enunciarlaPolitica',
    labelNombre: 'Enunciar la política del transportista ferroviario en materia de seguridad orientada a prevenir, asegurar y reconocer amenazas en la cadena de suministros y de todas sus instalaciones de la compañía.',
    campo: 'enunciarlaPolitica',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueQuienEsEl',
    labelNombre: 'Indique quién es el responsable de su revisión, firma y difusión hacia los empleados.',
    campo: 'indiqueQuienEsEl',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueLaPeriodicidad',
    labelNombre: 'Indique la periodicidad con la que se lleva a cabo su actualización.',
    campo: 'indiqueLaPeriodicidad',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueElProgramaCampana',
    labelNombre: 'Indique el programa y/o campaña de difusión que utiliza para comunicar a los empleados la política de seguridad en la cadena de suministros.',
    campo: 'indiqueElProgramaCampana',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueSiRealiza',
    labelNombre: 'Indique si realiza capacitación inicial y de reforzamiento de la política de seguridad en la cadena de suministros.',
    campo: 'indiqueSiRealiza',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
]

export const AUDITORIAS_INTERNAS = [
  {
    id: 'siCuentaConUnRealizacion',
    labelNombre: 'Si cuenta con un procedimiento documentado para su realización.',
    campo: 'siCuentaConUnRealizacion',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'describaElProcedimiento',
    labelNombre: 'Describa el procedimiento documentado para llevar a cabo una auditoría interna enfocada en la seguridad en la cadena de suministros.',
    campo: 'describaElProcedimiento',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 5,
  },
  {
    id: 'nombreDelProcedimiento',
    labelNombre: 'Nombre del procedimiento para llevar a cabo una auditoría interna enfocada en la seguridad en la cadena de suministros.',
    campo: 'nombreDelProcedimiento',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 5,
  },
  {
    id: 'senaleSiElEnfoque',
    labelNombre: 'Señale si el enfoque de las auditorías es en base al tamaño de la organización y a la naturaleza de los riesgos.',
    campo: 'senaleSiElEnfoque',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 5,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'indiqueQueProcesos',
    labelNombre: 'Indique que procesos o tópicos se auditan.',
    campo: 'indiqueQueProcesos',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 5,
  },
  {
    id: 'senaleSiCuentaConRegistros',
    labelNombre: 'Señale si cuenta con registros de los resultados de las auditorías y su seguimiento.',
    campo: 'senaleSiCuentaConRegistros',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 5,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'senalecomoLleva',
    labelNombre: 'Señale cómo lleva a cabo la programación o calendarización para realizar una auditoría interna en materia de seguridad en la cadena de suministros.',
    campo: 'senalecomoLleva',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 5,
  },
  {
    id: 'indiqueLosNombrePuestos',
    labelNombre: 'Indique los nombre y puestos de quienes participan, los registros que se efectúan y la periodicidad con la que se realizan las auditorías internas.',
    campo: 'indiqueLosNombrePuestos',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 5,
  },
  {
    id: 'indiqueSiLaGerencia',
    labelNombre: 'Indique si la gerencia de la empresa verifica el resultado de las auditorías en materia de seguridad, y si realiza y/o implementa acciones preventivas, correctivas y de mejora, además del seguimiento y cierre de las mismas.',
    campo: 'indiqueSiLaGerencia',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 5,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
]

export const PLANES_DE_CONTINGENCIA = [
  {
    id: 'indiqueCiCuentaTransportista',
    labelNombre: 'Indique si cuenta con procedimiento o plan de emergencia documentado, para asegurar la continuidad del negocio, en caso de una situación de emergencia o de seguridad, que pueden afectar el funcionamiento del transportista.',
    campo: 'indiqueCiCuentaTransportista',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'customSection1_planesContingencia',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 5,
    templateKey: 'customSection1',
  },
  {
    id: 'queSituacionesContempla',
    labelNombre: 'Qué situaciones contempla, describiendo el plan de acción y pasos que hay que seguir en caso de crisis, así como las tareas que el personal tenga asignadas durante el manejo de dichas contingencias.',
    campo: 'queSituacionesContempla',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 5,
  },
  {
    id: 'queMecanismosUtiliza',
    labelNombre: 'Qué mecanismos utiliza para difundir y asegurarse que los planes de contingencia son efectivos.',
    campo: 'queMecanismosUtiliza',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 5,
  },
  {
    id: 'indiqueSiCuentaContingencia',
    labelNombre: 'Indique si cuenta con registros de capacitaciones periódicas, pruebas, ejercicios prácticos o simulacros anuales de los planes de contingencia.',
    campo: 'indiqueSiCuentaContingencia',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'indiqueSiRealizaTraslados',
    labelNombre: 'Indique si realiza traslados de Materiales y Residuos Peligrosos.',
    campo: 'indiqueSiRealizaTraslados',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
]

export const INSTALACIONES = [
  {
    id: 'losMaterialesPredominantes',
    labelNombre: 'Los materiales predominantes con los que se encuentran construidas las instalaciones (por ejemplo, de estructura de metal y paredes de lámina, paredes de ladrillo, de madera, entre otros)',
    campo: 'losMaterialesPredominantes',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleDeQueForma',
    labelNombre: 'Señale de qué forma se lleva a cabo la revisión y mantenimiento de la integridad de las estructuras.',
    campo: 'senaleDeQueForma',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueElPersonal',
    labelNombre: 'Indique el personal o área responsable para realizar las tareas de inspección, mantenimiento y reparación de daños de las instalaciones.',
    campo: 'indiqueElPersonal',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'customSection1_instalaciones',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 5,
    templateKey: 'customSection1',
  },
]

export const ACCESO_EN_PUERTAS = [
  {
    id: 'indiqueCuantasPuertasAccesos',
    labelNombre: 'Indique cuantas puertas y/o accesos existen en las instalaciones, así como el horario de operación de cada una, e indique de qué forma son monitoreadas (en caso de tener personal asignado, indicar la cantidad).',
    campo: 'indiqueCuantasPuertasAccesos',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'detalleSiExistenPuertas',
    labelNombre: 'Detalle si existen puertas y/o accesos bloqueados, o permanentemente cerradas.',
    campo: 'detalleSiExistenPuertas',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'describaComoAsegura',
    labelNombre: 'Describa cómo asegura que el acceso a las áreas sensibles este restringido según la descripción del trabajo o las tareas asignadas (incluya el tipo de registros y controles que utiliza).',
    campo: 'describaComoAsegura',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const BARDAS_PERIMETRALES = [
  {
    id: 'describireltipo',
    labelNombre: 'Describir el tipo de cerca, barrera periférica y/o bardas con las que cuenta la empresa',
    campo: 'describireltipo',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleLasCaracteristicas',
    labelNombre: 'Señale las características de las mismas (material, dimensiones, etc.).',
    campo: 'senaleLasCaracteristicas',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'encasoDeNoContar',
    labelNombre: 'En caso de no contar con bardas, justificar detalladamente la razón',
    campo: 'encasoDeNoContar',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'periodicidadConla',
    labelNombre: 'Periodicidad con la que se verifica la integridad de las bardas perimétricas, y los registros que se llevan a cabo con la finalidad de asegurar su integridad e identificar daños, mismos que deben repararse lo antes posible.',
    campo: 'periodicidadConla',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueElPersonal',
    labelNombre: 'Indique el personal o área responsable para realizar las tareas de inspección y reparación de daños',
    campo: 'indiqueElPersonal',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueComoEstan',
    labelNombre: 'Indique cómo están divididos sus patios operativos ferroviarios.',
    campo: 'indiqueComoEstan',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'describaBrevemente',
    labelNombre: 'Describa brevemente, de qué forma separan los carros de ferrocarril o contenedores de carga doméstica y/o internacional, vacíos, en reparación y/o mantenimiento, talleres, entre otros.',
    campo: 'describaBrevemente',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const ESTACIONAMIENTOS = [
  {
    id: 'describaEstacionamientos',
    labelNombre: 'Describa el procedimiento para el control y monitoreo de los estacionamientos.',
    campo: 'describaEstacionamientos',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'responsablesEstacionamientos',
    labelNombre: 'Responsables de controlar y monitorear el acceso a los estacionamientos.',
    campo: 'responsablesEstacionamientos',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'identificacionDeLos',
    labelNombre: 'Identificación de los estacionamientos (especifique si el estacionamiento de empleados, visitantes, se encuentra separado de los equipos tractivos y de arrastre, (furgones, góndolas, tolvas, carros tanque, chasises, remolques, plataformas que no tienen tracción propia que circulan en las vías férreas y que utilizan para transportar mercancía en su interior y en contenedores) y manejo de mercancías.',
    campo: 'identificacionDeLos',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'comoSeLlevaElControl',
    labelNombre: 'Cómo se lleva el control de entrada y salida de vehículos a las instalaciones. Indique los registros que se realizan para el control del estacionamiento y los mecanismos de control existentes (por ejemplo: tarjetones, tarjetas lectoras, corbatines, etcétera), cómo se asignan y el área responsable de hacerlo.',
    campo: 'comoSeLlevaElControl',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'politicasOMecanismos',
    labelNombre: 'Políticas o mecanismos para no permitir el ingreso de vehículos privados a las áreas de almacenaje de medios de transporte y en su caso manejo de mercancía.',
    campo: 'politicasOMecanismos',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const CONTROL_DE_LLAVES = [
  {
    id: 'indiqueSiTodasLasPuertas',
    labelNombre: 'Indique si todas las puertas, ventanas, entradas interiores y exteriores disponen de mecanismos de cierre o seguridad.',
    campo: 'indiqueSiTodasLasPuertas',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'siCuentaConUnRegistro',
    labelNombre: 'Si cuenta con un registro de las personas que en base a sus funciones cuenten con llaves o accesos autorizados.',
    campo: 'siCuentaConUnRegistro',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'responsablesDeAdministrar',
    labelNombre: 'Responsables de administrar y controlar la seguridad de las llaves.',
    campo: 'responsablesDeAdministrar',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'formato_yo_Registro',
    labelNombre: 'Formato y/o registro de control para el préstamo de llaves.',
    campo: 'formato_yo_Registro',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'tratamientoDePerdida',
    labelNombre: 'Tratamiento de pérdida o no devolución de llaves.',
    campo: 'tratamientoDePerdida',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleSiExisten',
    labelNombre: 'Señale si existen áreas en las que se acceda con dispositivos electrónicos y/o algún otro mecanismo de acceso.',
    campo: 'senaleSiExisten',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'customSection2_ControlDeLLaves',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 5,
    templateKey: 'customSection2',
  },
]

export const ALUMBRADO = [
  {
    id: 'describaIluminacion',
    labelNombre: 'Describa el procedimiento para la operación y mantenimiento del sistema de iluminación.',
    campo: 'describaIluminacion',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleRespaldo',
    labelNombre: 'Señale qué áreas se encuentran iluminadas y cuáles cuentan con sistema de respaldo .',
    campo: 'senaleRespaldo',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueAuxiliar',
    labelNombre: 'Indique si cuenta con una planta de poder auxiliar.',
    campo: 'indiqueAuxiliar',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'mencioneContingencia',
    labelNombre: 'Mencione si cuenta con algún otro mecanismo para suministrar energía eléctrica en caso de alguna contingencia.',
    campo: 'mencioneContingencia',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'deQueManera',
    labelNombre: 'De qué manera se cerciora que el sistema de iluminación sea el apropiado en cada una de las áreas de la empresa, de manera que permita una clara identificación del personal, material y/o equipo que abarca.',
    campo: 'deQueManera',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueMantenimiento',
    labelNombre: 'Indique el responsable del control y mantenimiento de los sistemas de iluminación.',
    campo: 'indiqueMantenimiento',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'describaIndicarlo',
    labelNombre: 'Describa su programa de mantenimiento y revisión (en caso de coincidir con otro proceso, indicarlo).',
    campo: 'describaIndicarlo',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const APARATOS = [
  {
    id: 'describaIncidente',
    labelNombre: 'Describa el procedimiento que el personal debe realizar para contactar al personal de seguridad o, en su caso, con la autoridad correspondiente en caso de algún incidente.',
    campo: 'describaIncidente',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueReaccion',
    labelNombre: 'Indique si el personal operativo y administrativo cuenta o dispone de aparatos (teléfonos fijos, móviles, botones de alerta y/o emergencia) para comunicarse con el personal de seguridad y/o con quien corresponda. (Estos deberán estar accesibles a los usuarios, para poder tener una pronta reacción).',
    campo: 'indiqueReaccion',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'indiqueEtcetera',
    labelNombre: 'Indique qué aparatos de comunicación utiliza el personal de seguridad de la empresa concesionaria de transporte ferroviario (teléfonos fijos, celulares, radios, sistema de alarma, etcétera).',
    campo: 'indiqueEtcetera',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'describaComunicacion',
    labelNombre: 'Describa el procedimiento para el control y mantenimiento de los aparatos de comunicación:',
    campo: 'describaComunicacion',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'politicasMovil',
    labelNombre: 'Políticas de asignación de aparatos de comunicación móvil.',
    campo: 'politicasMovil',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'programaMovil',
    labelNombre: 'Programa de mantenimiento o reemplazo de aparatos de comunicación fija y móvil.',
    campo: 'programaMovil',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueSistemaPermanenteFallara',
    labelNombre: 'Indique si cuenta con aparatos de comunicación de respaldo, en caso de que el sistema permanente fallara, y, en su caso, detalle brevemente.',
    campo: 'indiqueSistemaPermanenteFallara',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiquePersonalDeSeguridad',
    labelNombre: 'Indique qué aparatos de comunicación utiliza el personal de seguridad de la empresa concesionaria de transporte ferroviario (teléfonos fijos, celulares, radios, sistema de alarma, etcétera).',
    campo: 'indiquePersonalDeSeguridad',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueTripulacion',
    labelNombre: 'Indique si la tripulación de la empresa utiliza teléfonos, radios, celulares, banda civil (CB), o algún otro medio para su comunicación interna y las políticas de asignación de los mismos',
    campo: 'indiqueTripulacion',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const SISTEMAS_DE_ALARMA = [
  {
    id: 'mencionarElProcedimiento',
    labelNombre: 'Mencionar el procedimiento en el que indique el funcionamiento del sistema central de alarmas externo o sensores.',
    campo: 'mencionarElProcedimiento',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueSensoresDeMovimiento',
    labelNombre: 'Indique si las puertas y ventanas tienen sensores de alarma o sensores de movimiento.',
    campo: 'indiqueSensoresDeMovimiento',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'describaActivarse',
    labelNombre: 'Describa el procedimiento a seguir en caso de activarse una alarma.',
    campo: 'describaActivarse',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'describaCircuitoCerrado',
    labelNombre: 'Describa el procedimiento para la operación de los sistemas de alarma y de circuito cerrado de televisión y video vigilancia y las tecnologías de seguridad (este debe revisarse y actualizarse anualmente y de acuerdo con el análisis de riesgo o las circunstancias).',
    campo: 'describaCircuitoCerrado',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueCamaras',
    labelNombre: 'Indique el número de cámaras de los sistemas de alarma y de circuito cerrado de televisión y video vigilancia instaladas, características técnicas y su ubicación (detalle si cubre los puntos de entrada y salida de las instalaciones, para cubrir el movimiento de vehículos e individuos, así como el lugar de almacenajes de los vehículos).',
    campo: 'indiqueCamaras',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'mencioneDonde',
    labelNombre: 'Mencione donde se lleva a cabo la inspección señalada en el sub-estándar 7.2.',
    campo: 'mencioneDonde',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleLaUbicacion',
    labelNombre: 'Señale la ubicación de los sistemas de alarma y de circuito cerrado de televisión y video vigilancia y las tecnologías de seguridad dónde se localizan los monitores, quién los revisa.',
    campo: 'senaleLaUbicacion',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueLosHorarios',
    labelNombre: 'Indique los horarios de operación, y en su caso, si existen estaciones de monitoreo remoto. Toda la infraestructura de tecnología de seguridad debe estar protegida físicamente contra el acceso no autorizado',
    campo: 'indiqueLosHorarios',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueGrabaciones',
    labelNombre: 'Indique de qué forma revisan las grabaciones (aleatoria, cada semana, eventos especiales, áreas restringidas, etcétera)',
    campo: 'indiqueGrabaciones',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueDesignado',
    labelNombre: 'Indique quién es el personal designado y cómo la gerencia se involucra en las revisiones.',
    campo: 'indiqueDesignado',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'comoDocumentan',
    labelNombre: 'Cómo se documentan los resultados de las revisiones para incluir acciones correctivas para fines de auditoría.',
    campo: 'comoDocumentan',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueTiempo',
    labelNombre: 'Indique por cuánto tiempo se mantienen estas grabaciones. (debiendo ser por lo menos de un mes).',
    campo: 'indiqueTiempo',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiquePoderElectrica',
    labelNombre: 'Indique si los sistemas de alarma y de circuito cerrado de televisión y video vigilancia y las tecnologías de seguridad se encuentran respaldadas por una planta de poder eléctrica.',
    campo: 'indiquePoderElectrica',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'enCasoDeNoContarFuncionamiento',
    labelNombre: 'En caso de no contar con una planta de poder eléctrica, mencione algún otro mecanismo para suministrar energía eléctrica, que garanticen su funcionamiento.',
    campo: 'enCasoDeNoContarFuncionamiento',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'estosSistemasDeberian',
    labelNombre: 'Estos sistemas deberían de tener una función de alarma/notificación, que indique una condición de falla en el funcionamiento y/ o grabación, señale si sus sistemas tienen dicha función.',
    campo: 'estosSistemasDeberian',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indicarSiAdicionalmente',
    labelNombre: 'Indicar si adicionalmente a los sistemas de alarma y de circuito cerrado de televisión y video vigilancia utiliza algún otro tipo de tecnología para robustecer las medidas de seguridad con las que ya cuenta.',
    campo: 'indicarSiAdicionalmente',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'describaImplementado',
    labelNombre: 'Describa el procedimiento que se ha implementado para probar e inspeccionar de manera regular los sistemas de alarma y de circuito cerrado de televisión y video vigilancia y las tecnologías de seguridad y asegurar su buen funcionamiento. Los resultados de las inspecciones y las pruebas de funcionamiento deben estar documentadas, al igual que las acciones correctivas necesarias (estas se deben implementar lo antes posible). Adicionalmente, que los resultados documentados de estas inspecciones se mantengan durante un tiempo suficiente para fines de auditoría.',
    campo: 'describaImplementado',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indicarSiElProveedor',
    labelNombre: 'Indicar si el proveedor de alarmas y sistemas de alarma y de circuito cerrado de televisión y video vigilancia tiene acceso a las cámaras de seguridad, si es el encargado de realizar el monitoreo de las mismas.',
    campo: 'indicarSiElProveedor',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'indiqueControlan',
    labelNombre: 'Indique de qué forma se controlan los accesos y quién es el responsable de dicho monitoreo.',
    campo: 'indiqueControlan',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const PERSONAL_DE_SEGURIDAD = [
  {
    id: 'describirDocumentadoSeguridad',
    labelNombre: 'Describir el procedimiento documentado para la operación del personal de seguridad.',
    campo: 'describirDocumentadoSeguridad',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueElNumeroDePersonal',
    labelNombre: 'Indique el número de personal de seguridad que labora en la empresa.',
    campo: 'indiqueElNumeroDePersonal',
    clase: 'col-md-12',
    tipoInput: 'number',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleLosCargosOperacion',
    labelNombre: 'Señale los cargos y/o funciones del personal y horarios de operación.',
    campo: 'senaleLosCargosOperacion',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'enCasoDeContratarse',
    labelNombre: 'En caso de contratarse un servicio externo,especificar número de personal empleado, detalles de operación, registros, reportes, etc.',
    campo: 'enCasoDeContratarse',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'enCasoLasArmas',
    labelNombre: 'En caso de contar con personal armado, describa el procedimiento para el control y resguardo de las armas.',
    campo: 'enCasoLasArmas',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const IDENTIFICACION_DE_LOS_EMPLEADOS = [
  {
    id: 'describaIdentificacionEmpleados',
    labelNombre: 'Describa el procedimiento para la identificación de los empleados.',
    campo: 'describaIdentificacionEmpleados',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueLosMecanismos',
    labelNombre: 'Indique los mecanismos de identificación (credencial con foto, uniforme, etcétera).',
    campo: 'indiqueLosMecanismos',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueSiLosEmpleados',
    labelNombre: 'Indique si los empleados utilizan uniformes, cómo son asignados (por puesto, área, funciones, etcétera) y retirados (en su caso).',
    campo: 'indiqueSiLosEmpleados',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueComoSeIdentifica',
    labelNombre: 'Indique cómo se identifica al personal contratado por un socio comercial, que labore dentro de las instalaciones. (Contratistas, Sub-contratados, etc.).',
    campo: 'indiqueComoSeIdentifica',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'describaComoAdministrar',
    labelNombre: 'Describa cómo la empresa entrega, cambia y retira las identificaciones y controles de acceso del empleado y asegúrese de incluir las áreas responsables de autorizarlas y administrar.',
    campo: 'describaComoAdministrar',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueComoAsegura',
    labelNombre: 'Indique cómo asegura que el acceso a las áreas sensibles este restringido según la descripción del trabajo o las tareas asignadas (incluya el tipo de registros y controles que utiliza',
    campo: 'indiqueComoAsegura',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'describaVisitantesYProveedores',
    labelNombre: 'Describa el procedimiento para el control de acceso de los visitantes y proveedores.',
    campo: 'describaVisitantesYProveedores',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleBitacoras',
    labelNombre: 'Señale qué registros se llevan a cabo. (Formatos personales por cada visita, bitácoras).',
    campo: 'senaleBitacoras',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueComoAsegura',
    labelNombre: 'Indique cómo asegura que el acceso a las áreas sensibles este restringido según la descripción del trabajo o las tareas asignadas (incluya el tipo de registros y controles que utiliza',
    campo: 'indiqueComoAsegura',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'customSection1_identificacion',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    templateKey: 'customSection1',
  },
  {
    id: 'senaleQuienIngreso',
    labelNombre: 'Señale quién es la persona responsable de acompañar al visitante y/o proveedor y si existen áreas restringidas para su ingreso.',
    campo: 'senaleQuienIngreso',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'customSection2_identificacion',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 5,
    templateKey: 'customSection2',
  },
]

export const ENTREGAS_DE_MENSAJERIA = [
  {
    id: 'describaPaqueteria',
    labelNombre: 'Describa el procedimiento para la recepción y revisión de mensajería y paquetería.',
    campo: 'describaPaqueteria',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleAlPersonalEncargado',
    labelNombre: 'Señale al personal encargado de llevar a cabo el procedimiento.',
    campo: 'senaleAlPersonalEncargado',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueComoSeIdentifica',
    labelNombre: 'Indique cómo se identifica al proveedor del servicio. (Señale si requiere de procedimiento adicional al de acceso a proveedores).',
    campo: 'indiqueComoSeIdentifica',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleDeQueForma',
    labelNombre: 'Señale de qué forma se revisan los paquetes y/o que mecanismo utiliza, así como los registros que se llevan a cabo y, en su caso, los incidentes detectados.',
    campo: 'senaleDeQueForma',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'senaleSospechoso',
    labelNombre: 'Señale qué acción realiza en el caso de detectar un paquete sospechoso.',
    campo: 'senaleSospechoso',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueIncidentesDetectados',
    labelNombre: 'Indique cómo se lleva a cabo el registro de la inspección y en su caso de los incidentes detectados.',
    campo: 'indiqueIncidentesDetectados',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const CRITERIO_DE_SELECCION = [
  {
    id: 'indiqueComoLlevaCabo',
    labelNombre: 'Indique cómo lleva a cabo su programa de cumplimiento social entre sus empleados y socios comerciales que, como mínimo, aborde cómo la empresa garantiza que los bienes, insumos o mercancías nacionales e importadas a México para la elaboración de productos o mercancías no provienen de la extracción, producción o fabricación, total o parcialmente, con formas prohibidas de trabajo, es decir, forzoso u obligado y cómo lo documenta.',
    campo: 'indiqueComoLlevaCabo',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const REQUERIMIENTOS_EN_SEGURIDAD = [
  {
    id: 'describaMateriaDeSeguridad',
    labelNombre: 'Describa el procedimiento que indique cómo lleva a cabo la identificación de socios comerciales que requieran el cumplimiento de estándares mínimos en materia de seguridad.',
    campo: 'describaMateriaDeSeguridad',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indicarSociosComerciales',
    labelNombre: 'Indicar los socios comerciales que deben cumplir con requisitos en materia de seguridad, y mencione qué tipo de proveedores son estos (Transportistas, Almacenes, Servicio de Custodios, Empresa de Seguridad, Servicios de Reparación de Medios de Transporte, Servicio de Carga y Descarga, Agentes Aduanales, etcétera).',
    campo: 'indicarSociosComerciales',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueFormaDocumental',
    labelNombre: 'Indique de qué forma documental (convenios, acuerdos, cláusulas contractuales y/o adendas), asegura que sus socios comerciales cumplan con los requisitos en materia de seguridad.',
    campo: 'indiqueFormaDocumental',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueSiExisten',
    labelNombre: 'Indique si existen convenios, acuerdos contractuales, cláusulas contractuales y/o adendas respecto a la implementación de medidas de seguridad con sus proveedores de servicios al interior de su empresa, tales como: seguridad, privadas, comedor, jardinería, servicios de limpieza y mantenimiento proveedores de Tecnología de la Información, etcétera.',
    campo: 'indiqueSiExisten',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueLesExija',
    labelNombre: 'Indique si cuenta con socios comerciales que se les exija pertenecer a un programa de seguridad de la cadena de suministros (por ejemplo: CTPAT o algún otro Programa de Operador Económico Autorizado de la OMA), así como la información y documentación que le son solicitadas.',
    campo: 'indiqueLesExija',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]

export const REVISIONS_OF_COMMERCIAL_PARTNERS = [
  {
    id: 'describaVerificacionDeLosRequisitos',
    labelNombre: 'Describa el procedimiento para la verificación de los requisitos en materia de seguridad de sus socios comerciales.',
    campo: 'describaVerificacionDeLosRequisitos',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'indiqueLaPeriodicidadSituaciones',
    labelNombre: 'Indique la periodicidad con la que realiza las visitas al socio comercial (estas deben de ser por lo menos una vez al año y derivadas de situaciones de riesgo).',
    campo: 'indiqueLaPeriodicidadSituaciones',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'describaElProgramaOCalendario',
    labelNombre: 'Describa el programa o calendario para la ejecución de las revisiones de seguridad.',
    campo: 'describaElProgramaOCalendario',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
   {
    id: 'indiqueElRegistroOReporte',
    labelNombre: 'Indique el registro o reporte de la verificación, y en su caso del seguimiento correspondiente.',
    campo: 'indiqueElRegistroOReporte',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
   {
    id: 'elOLosFormatosDeVerificacion',
    labelNombre: 'El o los formatos de verificación tendrán que estar debidamente requisitados, colocando la fecha, nombre y cargo de quienes participan en la revisión, firmas, etcétera.',
    campo: 'elOLosFormatosDeVerificacion',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
   {
    id: 'senalarQueMedidas',
    labelNombre: 'Señalar qué medidas de acción se toman en caso de que los socios comerciales no cumplan con los requisitos de seguridad establecidos.',
    campo: 'senalarQueMedidas',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
  {
    id: 'enCasoConformeOLoEstablecido',
    labelNombre: 'En caso de contar con socios comerciales con la certificación de CTPAT u otro programa de certificación de seguridad en la cadena de suministros, indique la periodicidad con la que es revisado su estatus, cómo lo registran y las acciones que toma en caso de detectarse que este suspendida y/o cancelado, conforme a lo establecido en su procedimiento.',
    campo: 'enCasoConformeOLoEstablecido',
    clase: 'col-md-12',
    tipoInput: 'textarea',
    desactivado: false,
    soloLectura: false,
    validadores: [{tipo: 'required'}],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 3,
  },
]