/**
 * @fileoverview
 * Este archivo contiene el servicio adaptador para convertir entre el estado de Akita y los formatos de payload de API
 * para el trámite de ampliación de servicios 80205.
 */

import { Injectable } from '@angular/core';
import { ProsecState } from '../estados/autorizacion-prosec.store';

@Injectable({
  providedIn: 'root'
})
export class GuardarMappingAdapter {
  /**
   * Convierte del estado de Akita al formato de payload de API usando las mismas claves
   * @param state El estado actual de Akita
   * @returns Payload formateado para la API
   */
  
  static toFormPayload(state: ProsecState): unknown {
    return {

       "tipoDeSolicitud": "guardar",
    "idSolicitud": 0,
    "cveUnidadAdministrativa": null,
    "costoTotal": null,
    "certificadoSerialNumber": null,
    "numeroFolioTramiteOriginal": null,
    "tipoSolicitud": 1,
    "folioPrograma": null,
    "fechaFinVigencia": null,
    "idProgramaAutorizado": null,
    "discriminatorValue": "90102",
    "solicitante": {
        "rfc": "AAL0409235E6",
        "domicilio": {
            "cvePais": "MEX",
            "cveEntidad": "SIN",
            "cveDelegMun": "25001",
            "cveColonia": "00181210001",
            "cveLocalidad": "00181210008",
            "nombrePais": "ESTADOS UNIDOS MEXICANOS",
            "codigoPostal": "81210",
            "nombreEntidad": "SINALOA",
            "nombreDelegMun": "AHOME",
            "nombreLocalidad": "LOS MOCHIS",
            "nombreColonia": "MIGUEL HIDALGO",
            "calle": "CAMINO VIEJO",
            "numExterior": "1353",
            "numInterior": null
        },
        "cveUsuario": "AAL0409235E6",
        "razonSocial": "INTEGRADORA DE URBANIZACIONES SIGNUM S DE RL DE CV",
        "descripcionGiro": "Siembra, cultivo y cosecha de otros cultivos",
        "correoElectronico": "vucem2021@gmail.com",
        "telefono": "55-98764532"
    },
    "anioPrograma": null,
    "idSolicitudSeleccionada": null,
    "inicio": 1,
    "repFedSol": null,
    "cveRolCapturista": "PersonaMoral",
    "cveUsuarioCapturista": "AAL0409235E6",
    "puedeCapturarRepresentanteLegalCG": false,
    "modalidad": "Productor indirecto",
    "entidadFederativaDomicilios": "SIN",
    "representacionesFederales": "2540",
    "actividadProductivaProsec": 3,
    "mensajeActivado": null,
    "sectoresProsecConf": "XIXa",
    "seleccionar": "50",
    "fraccion": null,
    "plantas": [
            {
                "recintoSolicitudPK": null,
                "razonSocial": null,
                "clavePlanta": null,
                "claveAduana": null,
                "superficie": null,
                "ubicacionColindancias": null,
                "capacidadProduccion": null,
                "capacidadProduccionUtilizada": null,
                "tipoLocal": null,
                "tipoEstablecimiento": null,
                "ubicacionEstablecimiento": null,
                "domicilio": null,
                "empresaSolicitante": null,
                "empresaDto": {
                    "idServicio": null,
                    "descripcionServicio": null,
                    "domicilioCompleto": "      ",
                    "numeroPrograma": null,
                    "tiempoPrograma": null,
                    "descripcionTestado": null,
                    "idCompuestoEmpresa": null,
                    "idServicioAutorizado": null,
                    "idEmpresa": null,
                    "tipoEmpresa": null,
                    "caracterEmpresa": null,
                    "montoExportacionesUSD": null,
                    "numeroProgramaDGCESE": null,
                    "porcentajeParticipacionAccionaria": null,
                    "porcentajeParticionAccionariaExt": null,
                    "nombre": null,
                    "apellidoPaterno": null,
                    "apellidoMaterno": null,
                    "razonSocial": "INTEGRADORA DE URBANIZACIONES SIGNUM S DE RL DE CV",
                    "rfc": "AAL0409235E6",
                    "certificada": null,
                    "correoElectronico": null,
                    "idDireccionSol": null,
                    "idSolicitud": null,
                    "testado": null,
                    "fechaInicioVigencia": null,
                    "fechaFinVigencia": null,
                    "blnActivo": null,
                    "domicilioSolicitud": {
                        "idDomicilio": null,
                        "calle": "",
                        "numExterior": "",
                        "numInterior": "",
                        "codigoPostal": null,
                        "informacionExtra": null,
                        "clave": null,
                        "coloniaEntity": {
                            "clave": null,
                            "nombre": "",
                            "fechaCaptura": null,
                            "cveDelegMun": null,
                            "cveLocalidad": null,
                            "cp": null,
                            "fechaInicioVigencia": null,
                            "fechaFinVigencia": null,
                            "satColonyCd": null,
                            "blnActivo": false,
                            "delegacionMunicipio": null
                        },
                        "cveLocalidad": "",
                        "cveDelegMun": null,
                        "delegacionMunicipio": {
                            "cveDelegMun": null,
                            "cveEntidad": null,
                            "nombre": "",
                            "fechaCaptura": null,
                            "fechaInicioVigencia": null,
                            "fechaFinVigencia": null,
                            "satMunicopality": null,
                            "blnActivo": false,
                            "entidadFederativa": null,
                            "colonias": null
                        },
                        "cveEntidad": null,
                        "entidadFederativa": {
                            "cveEntidad": null,
                            "nombre": "",
                            "codEntidadIdc": null,
                            "cvePais": null,
                            "pais": null,
                            "fechaCaptura": null,
                            "fechaInicioVigencia": null,
                            "fechaFinVigencia": null,
                            "activo": false
                        },
                        "cvePais": null,
                        "pais": {
                            "cvePais": null,
                            "nombre": "",
                            "fechaCaptura": null,
                            "cveMoneda": null,
                            "cvePaisWco": null,
                            "nombreAlterno": null,
                            "fecFinVigencia": null,
                            "fecIniVigencia": null,
                            "blnActivo": false,
                            "restriccion": null
                        },
                        "ciudad": null,
                        "telefono": null,
                        "fax": null,
                        "municipio": "",
                        "colonia": "",
                        "descUbicacion": null,
                        "cveCatalogo": null,
                        "telefonos": null,
                        "tipoDomicilio": null,
                        "localidad": {
                            "cveLocalidad": "",
                            "cveDelegMun": null,
                            "nombre": "",
                            "fechaCaptura": null,
                            "fecIniVigencia": null,
                            "fecFinVigencia": null,
                            "codigoPostal": null,
                            "satTownCode": null,
                            "blnActivo": false
                        }
                    }
                },
                "rfcRecinto": null,
                "numeroLicencia": null,
                "avisoFuncionamiento": null,
                "rfcResponsableSanitario": null,
                "correoElectronico": null,
                "fecFinVigencia": null,
                "testado": false,
                "estadoEvaluacionEntidad": null,
                "estadoEntidad": null,
                "original": null,
                "modificado": null,
                "tipoBodega": null,
                "tipoDeposito": null,
                "marbetesPrecintos": null,
                "idSolicitudRecursiva": null,
                "idRecintoRecursiva": null,
                "claveSidefi": null,
                "nacional": null,
                "numeroMovimientoVs": null,
                "descripcionNumeroBodega": null,
                "blnActivo": null,
                "booleanAlquilado": null,
                "blnCertificada": null,
                "blnGenerico1": null,
                "capacidadMaxAlmacenamiento": null,
                "cveUnidadAdministrativa": null,
                "cveUnidadMedidaCapacidad": null,
                "cveUnidadMedidaVolumen": null,
                "descripcionCertificador": null,
                "fechaInicioVigencia": null,
                "idAlmacenadoraMercancia": null,
                "idPersonaSolicitud": null,
                "tipoInmueble": null,
                "idTipoRecinto": null,
                "rfcCertificador": null,
                "superficieEtr": null,
                "superficieMarbetes": null,
                "volumenManejoRecinto": null,
                "idRecinto": 1,
                "domicilioDto": {
                    "idDomicilio": null,
                    "calle": "AV LA LUNA MZA 4 LTE 1",
                    "numExterior": "1353",
                    "numInterior": "",
                    "codigoPostal": "83600",
                    "informacionExtra": null,
                    "clave": null,
                    "coloniaEntity": {
                        "clave": null,
                        "nombre": "OTRA NO ESPECIFICADA EN EL CATALOGO",
                        "fechaCaptura": null,
                        "cveDelegMun": null,
                        "cveLocalidad": null,
                        "cp": null,
                        "fechaInicioVigencia": null,
                        "fechaFinVigencia": null,
                        "satColonyCd": null,
                        "blnActivo": false,
                        "delegacionMunicipio": null
                    },
                    "cveLocalidad": null,
                    "cveDelegMun": null,
                    "delegacionMunicipio": {
                        "cveDelegMun": "29005",
                        "cveEntidad": null,
                        "nombre": "APIZACO",
                        "fechaCaptura": null,
                        "fechaInicioVigencia": null,
                        "fechaFinVigencia": null,
                        "satMunicopality": null,
                        "blnActivo": false,
                        "entidadFederativa": null,
                        "colonias": null
                    },
                    "cveEntidad": null,
                    "entidadFederativa": {
                        "cveEntidad": "SIN",
                        "nombre": "SONORA",
                        "codEntidadIdc": null,
                        "cvePais": null,
                        "pais": null,
                        "fechaCaptura": null,
                        "fechaInicioVigencia": null,
                        "fechaFinVigencia": null,
                        "activo": false
                    },
                    "cvePais": null,
                    "pais": {
                        "cvePais": null,
                        "nombre": "ESTADOS UNIDOS MEXICANOS",
                        "fechaCaptura": null,
                        "cveMoneda": null,
                        "cvePaisWco": null,
                        "nombreAlterno": null,
                        "fecFinVigencia": null,
                        "fecIniVigencia": null,
                        "blnActivo": false,
                        "restriccion": null
                    },
                    "ciudad": null,
                    "telefono": null,
                    "fax": null,
                    "municipio": null,
                    "colonia": null,
                    "descUbicacion": null,
                    "cveCatalogo": null,
                    "telefonos": null,
                    "tipoDomicilio": null,
                    "localidad": {
                        "cveLocalidad": "00590378998",
                        "cveDelegMun": null,
                        "nombre": "OTRA NO ESPECIFICADA EN EL CATALOGO",
                        "fechaCaptura": null,
                        "fecIniVigencia": null,
                        "fecFinVigencia": null,
                        "codigoPostal": null,
                        "satTownCode": null,
                        "blnActivo": false
                    }
                },
                "errorImmex": null,
                "domiciliosMontoInversion": null,
                "domiciliosEmpleados": null,
                "domiciliosCapacidad": null,
                "complementoPlanta": null,
                "firmantes": null
            }
        ],
    "sectores": [
        {
            "sector": "De la Industria Automotriz y de Autopartes a)",
            "cvSectorCatalogo": "XIXa",
            "descripcionTestado": null,
            "cveSector": null,
            "idConfProgramaSE": 50,
            "testadoSector": false,
            "visible": false,
            "fecIniVigencia": null,
            "fecFinVigencia": null,
            "idSolicitud": null,
            "solicitud": null
        }
    ],
    "fraccionSeleccionada": [
        {
            "complemento": null,
            "fraccionCompuesta": "8486400150",
            "cveServicioImmex": null,
            "cveSector": "XIXa",
            "idSectorProsecSol": null,
            "blnFraccionSeleccionada": 0,
            "descripcionTestado": null,
            "bienesProducidos": null,
            "proyectosImmex": null,
            "proyectosClientes": null,
            "nicoDtos": null,
            "claveProductoExportacion": null,
            "idSolicitud": null,
            "solicitud": null,
            "cveFraccion": null,
            "fraccionArancelaria": {
                "fraccionPadre": null,
                "descripcionFraccionPadre": null,
                "tipoFraccion": null,
                "exenta": null,
                "fraccionCompuesta": null,
                "claveFraccionPadre": null,
                "unidadMedida": null,
                "fraccionConcatenada": null,
                "descripcionTestado": null,
                "testado": false,
                "tipoOperacion": null,
                "valorMonedaMensual": null,
                "valorMonedaAnual": null,
                "valorProduccionMensual": null,
                "valorProduccionAnual": null,
                "valorProduccionAnualSolicitada": null,
                "claveCategoria": null,
                "descripcionCategoria": null,
                "mensaje": null,
                "descripcionUsuario": null,
                "umt": null,
                "idFraccion": null,
                "idProducto": null,
                "idProductoPadre": null,
                "claveProductoExportacion": null,
                "descripcionServicio": null,
                "rowID": null,
                "cveFraccion": "84864001",
                "capitulo": null,
                "partida": null,
                "subPartida": null,
                "descripcion": null,
                "fechaCaptura": null,
                "fechaInicioVigencia": null,
                "fechaFinVigencia": null,
                "cveUsuario": null,
                "cveCapituloFraccion": null,
                "cvePartidaFraccion": null,
                "cveSubPartidaFraccion": null,
                "activo": null,
                "activoAnexo28": null,
                "decretoImmex": null,
                "sector": null,
                "cveServicioImmex": null,
                "listaProveedores": null,
                "listaProyecto": null,
                "nicoDtos": null
            },
            "sector": {
                "sector": null,
                "cvSectorCatalogo": null,
                "descripcionTestado": null,
                "cveSector": null,
                "idConfProgramaSE": 50,
                "testadoSector": false,
                "visible": false,
                "fecIniVigencia": null,
                "fecFinVigencia": null,
                "idSolicitud": null,
                "solicitud": null
            },
            "testado": false,
            "claveServicioImmex": null,
            "tipoFraccion": null,
            "visible": false,
            "fraccionPadre": null,
            "fecIniVigencia": null,
            "fecFinVigencia": null,
            "replica": false,
            "activo": null,
            "idProductoExp": null
        }
    ]
    
    }
  }
}