apiVersion: apps/v1
kind: Deployment
metadata:
  name: modulefederation-agricultura-microfront-deployment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modulefederation-agricultura-microfront-dev
  template:
    metadata:
      labels:
        app: modulefederation-agricultura-microfront-dev
    spec:
      containers:
      - name: modulefederation-agricultura-microfront-deployment-dev
        image: ghcr.io/vucem30/dockerized-modulefederation-agricultura-microfront:latest
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
      imagePullSecrets:
      - name: vucem30registrykey
