import { ConfiguracionColumna } from "@libs/shared/data-access-user/src";
import { NumeroDeEmpleados } from "../models/datos-comunes-tres.model";

export const DATOS_COMUNES = [
  {
    id: 'catseleccionados',
    labelNombre: 'Sector Productivo',
    campo: 'catseleccionados',
    clase: 'col-md-6',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0
  },
  {
    id: 'servicio',
    labelNombre: 'Servicio',
    campo: 'servicio',
    clase: 'col-md-6',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
  },
  {
    id: '',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 5,
    templateKey: 'customSection1',
  },
  {
    id: 'senaleAduaneras',
    labelNombre: 'Señale si al momento de ingresar su solicitud si se encuentra al corriente en el cumplimiento de sus obligaciones fiscales y aduaneras',
    campo: 'senaleAduaneras',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'indiqueSiAutorizo',
    labelNombre: 'Indique si autorizó al S A T hacer pública su opinión positiva sobre el cumplimiento de obligaciones fiscales',
    campo: 'indiqueSiAutorizo',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'senaleSiCuenta',
    labelNombre: 'Señale si cuenta con empleados propios para realizar el proceso productivo o la prestación de servicios, registrado ante elIMSS',
    campo: 'senaleSiCuenta',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'cualEsElNumero',
    labelNombre: 'Cual es el número de empleados propios con los que contó en el último bimestre anterior a su solicitud',
    campo: 'cualEsElNumero',
    clase: 'col-md-12',
    tipoInput: 'label-only',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 5,
    mostrar: false,
  },
  {
    id: 'empleados',
    labelNombre: 'Número de empleados',
    campo: 'empleados',
    clase: 'col-md-6',
    tipoInput: 'text',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    mostrar: false,
  },
   {
    id: 'bimestre',
    labelNombre: 'Bimestre',
    campo: 'bimestre',
    clase: 'col-md-6',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    opciones: [],
    mostrar: false,
  },
  {
    id: 'cumpleConLaObligacion',
    labelNombre: 'Cumple con la obligación de retener y enterar el I S R de los trabajadores',
    campo: 'cumpleConLaObligacion',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'acreditaRealizar',
    labelNombre: 'Acredita realizar el pago de cuotas obrero patronales',
    campo: 'acreditaRealizar',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: 'senaleEspecializadas',
    labelNombre: 'Señale si al momento de ingresar su solicitud la empresa solicitante cuenta con subcontratación de servicios especializados o de ejecución de obras especializadas',
    campo: 'senaleEspecializadas',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true
  },
  {
    id: '',
    labelNombre: '',
    campo: '',
    clase: 'col-md-12',
    tipoInput: 'custom-html',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 5,
    templateKey: 'customSection2',
  },
  {
    id: 'enSuCasoLFT',
    labelNombre: 'En su caso, acredite cumplir con el registro y estar en el padrón a que se refiere el artículo 15 de la LFT.',
    campo: 'enSuCasoLFT',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
    mostrar: false,
  },
  {
    id: 'senaleSiAlMomentoFraccionVI',
    labelNombre: 'Señale si al momento de ingresar su solicitud se encuentra en el listado de empresas publicadas por el SAT en términos del artículo 69, con excepción de lo dispuesto en la fracción VI.',
    campo: 'senaleSiAlMomentoFraccionVI',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'delMismoModo',
    labelNombre: 'Del mismo modo, indique si al momento de ingresar su solicitud se encuentra en el listado de empresas publicadas por el SAT en términos del artículo 69-B, cuarto párrafo del CFF.',
    campo: 'delMismoModo',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'senaleSiSeEncuentraCFF',
    labelNombre: 'Señale si se encuentra en el listado de empresas publicadas por el SAT en términos del artículo 69-B Bis noveno párrafo del CFF.',
    campo: 'senaleSiSeEncuentraCFF',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'senaleSiSusCertificados',
    labelNombre: 'Señale si sus certificados de sellos digitales están vigentes.',
    campo: 'senaleSiSusCertificados',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'enCasoAfirmativoSenale',
    labelNombre: 'En caso afirmativo señale si se infringió alguno de los supuestos previstos en el artículo 17-H Bis del CFF, durante los últimos doce meses.',
    campo: 'enCasoAfirmativoSenale',
    clase: 'col-md-12',
    tipoInput: 'radio',
    desactivado: false,
    soloLectura: false,
    validadores: [{ tipo: 'required' }],
    valorPredeterminado: '',
    marcadorDePosicion: '',
    marginTop: 0,
    opciones: [
      {
        label: 'Si',
        value: 'Si',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
    gridLayout: true,
  },
  {
    id: 'indiqueTodos',
    labelNombre: '',
    campo: 'indiqueTodos',
    clase: 'col-md-6',
    tipoInput: 'select-catalogos',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 0,
    opciones: []
  },
  {
    id: 'indiqueTodosLosDomicilios',
    labelNombre: 'Indique todos los domicilios registrados ante el RFC del solicitante e indique aquellos en que se desarrollen actividades relacionadas con su proceso productivo y/o la prestación de servicios.',
    campo: 'indiqueTodosLosDomicilios',
    clase: 'col-md-12',
    tipoInput: 'label-only',
    desactivado: false,
    soloLectura: false,
    validadores: [],
    marcadorDePosicion: '',
    valorPredeterminado: '',
    marginTop: 3,
  },
];

/**
 * Configuración de columnas para la tabla de Número de Empleados.
 * Cada objeto en el arreglo define los detalles de una columna.
 * La clave indica el valor que se mostrará y el orden define la posición de la columna en la tabla.
 */
export const NUMERO_DE_EMPLEADOS_CONFIGURACION: ConfiguracionColumna<NumeroDeEmpleados>[] =
  [
    {
      encabezado: 'Denominacion Social',
      clave: (item: NumeroDeEmpleados) => item.denominacion,
      orden: 1,
    },
    {
      encabezado: 'RFC',
      clave: (item: NumeroDeEmpleados) => item.RFC,
      orden: 2,
    },
    {
      encabezado: 'Numero de Empleados',
      clave: (item: NumeroDeEmpleados) => item.numeroDeEmpleados,
      orden: 3,
    },
    {
      encabezado: 'Bimestre',
      clave: (item: NumeroDeEmpleados) => item.bimestre,
      orden: 4,
    },
  ];