export const PROGRAMA_SELECCIONADO = [
    {
        id: 'folioDePrograma',
        labelNombre: 'Folio de programa',
        campo: 'folioDePrograma',
        clase: 'col-md-4',
        tipoInput: 'text',
        desactivado: true,
        soloLectura: false,
        marcadorDePosicion: '',
        valorPredeterminado: '',
        marginTop: 0,
      },
      {
        id: 'seleccionaLaModalidad',
        labelNombre: 'Selecciona la modalidad',
        campo: 'seleccionaLaModalidad',
        clase: 'col-md-4',
        tipoInput: 'text',
        desactivado: true,
        soloLectura: false,
        marcadorDePosicion: '',
        valorPredeterminado: '',
        marginTop: 0,
      },
      {
        id: 'representacionFederal',
        labelNombre: 'Representación federal',
        campo: 'representacionFederal',
        clase: 'col-md-4',
        tipoInput: 'text',
        desactivado: true,
        soloLectura: false,
        marcadorDePosicion: '',
        valorPredeterminado: '',
        marginTop: 0,
      },
      {
        id: 'tipoPrograma',
        labelNombre: 'Tipo programa',
        campo: 'tipoPrograma',
        clase: 'col-md-4',
        tipoInput: 'text',
        desactivado: true,
        soloLectura: false,
        marcadorDePosicion: '',
        valorPredeterminado: '',
        marginTop: 0,
      },
      {
        id: 'estatus',
        labelNombre: 'Estatus',
        campo: 'estatus',
        clase: 'col-md-4',
        tipoInput: 'text',
        desactivado: true,
        soloLectura: false,
        marcadorDePosicion: '',
        valorPredeterminado: '',
        marginTop: 0,
      },
    {
      id: '',
      labelNombre: '',
      campo: '',
      clase: 'col-md-4',
      tipoInput: '',
      desactivado: false,
      soloLectura: false,
      validadores: [],
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    }, 
    {
        id: 'motivoCancelacion',
        labelNombre: 'Motivo cancelación',
        campo: 'motivoCancelacion',
        clase: 'col-md-12',
        tipoInput: 'textarea',
        desactivado: false,
        soloLectura: false,
        validadores: [{ tipo: 'required' }],
        marcadorDePosicion: '',
        valorPredeterminado: '',
        marginTop: 0,
      },
  ];