export const PROGRAMA_SELECCIONADO = [
    {
        id: 'folioDePrograma',
        labelNombre: 'Folio de programa',
        campo: 'folioDePrograma',
        clase: 'col-md-4',
        tipoInput: 'text',
        desactivado: true,
        soloLectura: false,
        marcadorDePosicion: '2024-9421',
        valorPredeterminado: '',
        marginTop: 0,
      },
      {
        id: 'seleccionaLaModalidad',
        labelNombre: 'Selecciona la modalidad',
        campo: 'seleccionaLaModalidad',
        clase: 'col-md-4',
        tipoInput: 'text',
        desactivado: true,
        soloLectura: false,
        marcadorDePosicion: 'PROGRAMA NUEVO PRODUCTOR DIRECTO',
        valorPredeterminado: '',
        marginTop: 0,
      },
      {
        id: 'representacionFederal',
        labelNombre: 'Representación federal',
        campo: 'representacionFederal',
        clase: 'col-md-4',
        tipoInput: 'text',
        desactivado: true,
        soloLectura: false,
        marcadorDePosicion: 'CULIACAN',
        valorPredeterminado: '',
        marginTop: 0,
      },
      {
        id: 'tipoPrograma',
        labelNombre: 'Tipo programa',
        campo: 'tipoPrograma',
        clase: 'col-md-4',
        tipoInput: 'text',
        desactivado: true,
        soloLectura: false,
        marcadorDePosicion: 'PROSEC',
        valorPredeterminado: '',
        marginTop: 0,
      },
      {
        id: 'estatus',
        labelNombre: 'Estatus',
        campo: 'estatus',
        clase: 'col-md-4',
        tipoInput: 'text',
        desactivado: true,
        soloLectura: false,
        marcadorDePosicion: 'Vigente - Activo',
        valorPredeterminado: '',
        marginTop: 0,
      },
    {
      id: '',
      labelNombre: '',
      campo: '',
      clase: 'col-md-4',
      tipoInput: '',
      desactivado: false,
      soloLectura: false,
      validadores: [],
      marcadorDePosicion: '',
      valorPredeterminado: '',
      marginTop: 0,
    }, 
    {
        id: 'motivoCancelacion',
        labelNombre: 'Motivo cancelación',
        campo: 'motivoCancelacion',
        clase: 'col-md-12',
        tipoInput: 'textarea',
        desactivado: false,
        soloLectura: false,
        validadores: [{ tipo: 'required' }],
        marcadorDePosicion: '',
        valorPredeterminado: '',
        marginTop: 0,
      },
  ];

  export const ALERTA_DE_APLICACION_REGISTRADA = {
    message: `
    <p>La solicitud ha quedado registrada con el número temporal 202770947. Este no tiene validez legal y sirve solamente para efectos de identificar tu solicitud. Un folio oficial será asignado a la solicitud en el momento en que esta sea firmada.</a>`
  };

  export const ERROR_FORMA_ALERT =
'<strong>¡Error de registro! </strong>Faltan campos por capturar.';