export const PASOS = [
    {
        indice: 1,
        titulo: 'Capturar solicitud',
        activo: true,
        completado: true,
    },
    {
        indice: 2,
        titulo: 'Requisitos necesarios',
        activo: false,
        completado: false,
    },
    {
        indice: 3,
        titulo: 'Anexar necesarios',
        activo: false,
        completado: false,
    },
    {
        indice: 4,
        titulo: 'Firmar solicitud',
        activo: false,
        completado: false,
    },
];

export const DATOS_GENERALES_SOLICITANTE = [
    {
        labelNombre: 'Registro federal de contribuyentes:',
        campo: 'Registro federal de contribuyentes:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        tooltip: 'Registro federal de contribuyentes:',
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Denominación o razón social',
        campo: 'Denominacion o razon social',
        class: 'col-md-8',
        tipo_input: 'text',
        disabled: true,
        tooltip: 'Denominacion o razon social',
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Actividad económica preponderante:',
        campo: 'Actividad económica preponderante',
        class: 'col-md-12',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Correo electrónico',
        campo: 'Correo electrónico',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    }
];

export const DOMICILIO_FISCAL_SOLICITANTE = [
    {
        labelNombre: 'País:',
        campo: 'País:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        tooltip: 'País:',
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Código postal:',
        campo: 'Código postal',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        tooltip: 'Código postal',
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Estado:',
        campo: 'Estado',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Municipio o alcaldía:',
        campo: 'Municipio o alcaldía:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Localidad:',
        campo: 'Localidad:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Colonia:',
        campo: 'Colonia:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Calle:',
        campo: 'Calle:',
        class: 'col-md-8',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Número exterior:',
        campo: 'Número exterior:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Número interior:',
        campo: 'Número interior:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Lada:',
        campo: 'Lada:',
        class: 'col-md-1',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Teléfono:',
        campo: 'Teléfono:',
        class: 'col-md-3',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    }
];

export const DATOS_REALIZAR = [
    {
        labelNombre: 'Régimen al que destinará la mercancía:',
        required: true,
        primerOpcion: 'Selecciona un valor',
        catalogos: [],
    },
    {
        labelNombre: 'Clasificación de regimen:',
        required: true,
        primerOpcion: 'Selecciona un valor',
        catalogos: [],
    }
];

export const DATOS_MERCANCIA = [
    {
        labelNombre: 'Descripción de la mercancía',
        campo: 'Descripción de la mercancía',
        class: 'col-md-8',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Marca(s) comercial(es) y Modelo(s):',
        campo: 'Marca(s) comercial(es) y Modelo(s):',
        class: 'col-md-8',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Tipo de aduana de entrada:',
        required: true,
        primerOpcion: 'Selecciona un valor',
        catalogos: [],
    },
    {
        labelNombre: 'Fracción arancelaria:',
        required: true,
        primerOpcion: 'Selecciona un valor',
        catalogos: [],
    },
    {
        labelNombre: 'NICO:',
        required: true,
        primerOpcion: 'Selecciona un valor',
        catalogos: [],
    },
    {
        labelNombre: 'Unidad de medida la tarifa(UMT):',
        required: true,
        primerOpcion: 'Selecciona un valor',
        catalogos: [],
    },
    {
        labelNombre: 'Número de factura:',
        campo: 'Número de factura:',
        class: 'col-md-8',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Fecha de factura:',
        required: true,
        habilitado: true,
    },
    {
        labelNombre: 'Unidad de medida de comercialización(UMC):',
        required: true,
        primerOpcion: 'Selecciona un valor',
        catalogos: [],
    },
    {
        labelNombre: 'Otro UMC:',
        campo: 'Otro UMC:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Cantidad UMC:',
        campo: 'Cantidad UMC:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Factor de conversión:',
        campo: 'Factor de conversión:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Cantidad UMT:',
        campo: 'Cantidad UMT:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Valor de la factura de la mercancía a importar en términos de la Moneda de comercialización:',
        campo: 'Valor de la factura de la mercancía a importar en términos de la Moneda de comercialización:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Moneda de comercialización:',
        required: true,
        primerOpcion: 'Selecciona una opcion',
        catalogos: [],
    },
    {
        labelNombre: 'Valor de la factura en USD de la mercancía a importar:',
        campo: 'Valor de la factura en USD de la mercancía a importar:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Precio unitario en USD:',
        campo: 'Precio unitario en USD:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'País exportador:',
        required: true,
        primerOpcion: 'Selecciona el País',
        catalogos: [],
    },
    {
        labelNombre: 'País origen:',
        required: true,
        primerOpcion: 'Selecciona el País',
        catalogos: [],
    },
    {
        labelNombre: 'valor total de la factura en terminos de la Moneda de comercialización:',
        campo: 'valor total de la factura en terminos de la Moneda de comercialización:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'valor total de la factura USD de la mercancía a importar:',
        campo: 'valor total de la factura USD de la mercancía a importar:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
];

export const DATOS_EXPORTACION = [
    {
        labelNombre: 'Número de documento:',
        campo: 'Número de documento:',
        class: 'col-md-8',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Fecha del documento:',
        required: true,
        habilitado: true,
    },
    {
        labelNombre: 'Descripción de la mercancía',
        campo: 'Descripción de la mercancía',
        class: 'col-md-8',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'código arancelario:',
        campo: 'código arancelario:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Cantidad en la unidad de medida senalada en el documento de exportacion:',
        campo: 'Cantidad en la unidad de medida senalada en el documento de exportacion:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Valor en USD de la mercancía a importar',
        campo: 'Valor en USD de la mercancía a importar',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
    {
        labelNombre: 'Precio unitario en USD:',
        campo: 'Precio unitario en USD:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
    },
];

export const DATOS_PRODUCTOR = [
    {
        labelNombre: 'Tipo de persona',
        required: true,
        options: [],
        selectedValue: '',
    },
    {
        labelNombre: 'Datos personales Nombre(s):',
        campo: 'Datos personales Nombre(s):',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Física',],
    },
    {
        labelNombre: 'Primer apellido:',
        campo: 'Primer apellido:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Física',],
    },
    {
        labelNombre: 'Segundo apellido:',
        campo: 'Segundo apellido:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Física',],
    },
    {
        labelNombre: 'Denominación o razón social',
        campo: 'Denominación o razón social',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Moral'],
    },
    {
        labelNombre: 'Domicilio:',
        campo: 'Domicilio:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Física', 'Moral', 'Ninguno'],
        
    },
];

export const DATOS_EXPORTADOR = [
    {
        labelNombre: 'Tipo de persona',
        required: true,
        options: [],
        selectedValue: '',
    },
    {
        labelNombre: 'Datos personales Nombre(s):',
        campo: 'Datos personales Nombre(s):',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Física',],
    },
    {
        labelNombre: 'Primer apellido:',
        campo: 'Primer apellido:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Física',],
    },
    {
        labelNombre: 'Segundo apellido:',
        campo: 'Segundo apellido:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Física',],
    },
    {
        labelNombre: 'Denominación o razón social',
        campo: 'Denominación o razón social',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Moral'],
    },
    {
        labelNombre: 'Domicilio:',
        campo: 'Domicilio:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Física', 'Moral'], 
    },
    {
        labelNombre: 'Observaciones:',
        campo: 'Observaciones:',
        class: 'col-md-4',
        tipo_input: 'text',
        disabled: true,
        validators: ['required'],
        placeholder: '',
        availableRadioOptions: ['Física', 'Moral'], 
    },
];