# Expose the deployment using a Service
apiVersion: v1
kind: Service
metadata:
  name: modulefederation-agricultura-microfront-service-qa
spec:
  selector:
    app: modulefederation-agricultura-microfront-qa
  ports:
    - protocol: TCP
      port: 4204
      targetPort: 80
  type: NodePort
