import { ImmexRegistroState } from "../estados/tramites/tramite80203.store";

export function buildGuardarPayload(storeData: ImmexRegistroState): unknown {
  return {
    tipoDeSolicitud: "guardar",
    idSolicitud: 0,
    idTipoTramite: 80203,
    rfc: "AAL0409235E6",
    cveUnidadAdministrativa: "8203",
    costoTotal: 10000.5,
    certificadoSerialNumber: "1234567890ABCDEF",
    certificado: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A",
    numeroFolioTramiteOriginal: "TRM-2023-00001",
    nombre: "Juan",
    apPaterno: "Pérez",
    apMaterno: "López",
    telefono: "5551234567",
    discriminatorValue: "80203",
    productoExportacionDtoList: (storeData.fraccionTablaDatos ?? []).map(item => ({
        fraccionArancelaria: {
            fraccionPadre: item.fraccionPadre,
            tipoFraccion: null,
            descripcionUsuario: item.descripcionUsuario,
            umt: item.umt,
            idFraccion: item.idFraccion,
            idProductoPadre: null,
            claveProductoExportacion: null,
            descripcion: item.descripcion,
            descripcionFraccionPadre: "string",
            exenta: true,
            fraccionCompuesta: "string",
            claveFraccionPadre: "string",
            unidadMedida: "string",
            fraccionConcatenada: "string",
            descripcionTestado: "string",
            testado: true,
            tipoOperacion: "string",
            valorMonedaMensual: "string",
            valorMonedaAnual: "string",
            valorProduccionMensual: "string",
            valorProduccionAnual: "string",
            valorProduccionAnualSolicitada: "string",
            claveCategoria: "string",
            descripcionCategoria: "string",
            mensaje: "string",
            idProducto: "stri",
            descripcionServicio: "string",
            rowID: "string",
            cveFraccion: "61032301",
            capitulo: "string",
            partida: "string",
            subPartida: "string",
            fechaCaptura: "2025-09-07T12:43:35.647Z",
            fechaInicioVigencia: "2025-09-07T12:43:35.647Z",
            fechaFinVigencia: "2025-09-07T12:43:35.647Z",
            cveUsuario: "string",
            cveCapituloFraccion: "string",
            cvePartidaFraccion: "string",
            cveSubPartidaFraccion: "string",
            activo: true,
            activoAnexo28: true,
            decretoImmex: true,
            sector: [
            {
                cveSector: "string",
                nombre: "string",
                productorIndirecto: 0,
                ampliacionMercancias: 0,
                fechaInicioVigencia: "2025-09-07T12:43:35.647Z",
                fechaFinVigencia: "2025-09-07T12:43:35.647Z",
                blnActivo: 0
            }
            ],
            cveServicioImmex: {
            claveServicio: "string",
            nombre: "string",
            tipoServicio: "string",
            fechaInicioVigencia: "2025-09-07T12:43:35.647Z",
            fechaFinVigencia: "2025-09-07T12:43:35.647Z",
            blnActivo: true
            },
            listaProveedores: [
            {
                idProveedor: "string",
                paisOrigen: "string",
                rfcProveedor: "string",
                razonProveedor: "string",
                paisDestino: "string",
                rfcCliente: "string",
                razonCliente: "string",
                domicilio: "string",
                testado: true,
                idProductoP: "string",
                descTestado: "string"
            }
            ],
            listaProyecto: [
            {
                idProyecto: "string",
                tipoDocumento: "string",
                descDocumento: "string",
                otro: "string",
                fechaIncio: "string",
                fechaFin: "string",
                firmante: {
                idFirmante: "string",
                rfc: "string",
                razonSocial: "string",
                claveFraccion: "string"
                },
                testado: "string",
                idProducto: "stri",
                descTestado: "string"
            }
            ],
            nicoDtos: storeData.nicoTablaDatosExportacion
        }
    })),
    mercanciaImportacion: [
        {
        claveMercanciaImportacion: 0,
        testado: 0,
        tipoFraccion: "string",
        visible: true,
        fraccionPadre: "string",
        blnFraccionSeleccionada: 0,
        claveFraccionPadre: "string",
        fraccionCompuesta: "string",
        descripcionTestado: "string",
        unidadMedida: "string",
        tipoOperacion: "string",
        valorMonedaMensual: "string",
        valorMonedaAnual: storeData.candiadAnual,
        valorProduccionMensual: storeData.capacidadPeriodo,
        valorProduccionAnual: storeData.candidadPorPeriodo,
        valorProduccionAnualSolicitada: "string",
        categoria: "string",
        mensaje: "string",
        umt: "string",
        claveCategoria: "string",
        descripcionUsuario: "string",
        descripcionFraccionPadre: "string",
        idProductoPadre: "string",
        idProducto: "stri",
        permisoPadre: "string",
        fraccionArancelaria: {
            capitulo: "61",
            partida: "6103",
            subPartida: "610323",
            descripcion: "De fibras sinteticas.",
            fechaCaptura: "2010-01-01",
            fechaInicioVigencia: "2010-01-01",
            fechaFinVigencia: null,
            cveUsuario: "RECE670302IU0",
            cveCapituloFraccion: "61",
            cvePartidaFraccion: "03",
            cveSubPartidaFraccion: "23",
            activo: true,
            activoAnexo28: false,
            decretoImmex: true,
            fraccionPadre: "string",
            descripcionFraccionPadre: "string",
            tipoFraccion: "string",
            exenta: true,
            fraccionCompuesta: "string",
            claveFraccionPadre: "string",
            unidadMedida: "string",
            fraccionConcatenada: "string",
            descripcionTestado: "string",
            testado: true,
            tipoOperacion: "string",
            valorMonedaMensual: "string",
            valorMonedaAnual: "string",
            valorProduccionMensual: "string",
            valorProduccionAnual: "string",
            valorProduccionAnualSolicitada: "string",
            claveCategoria: "string",
            descripcionCategoria: "string",
            mensaje: "string",
            descripcionUsuario: "string",
            umt: "string",
            idFraccion: "string",
            idProducto: "stri",
            idProductoPadre: "string",
            claveProductoExportacion: 0,
            descripcionServicio: "string",
            rowID: "string",
            cveFraccion: "61032301"
        },
        listaProveedores: [
            {
            idProveedor: "string",
            paisOrigen: "string",
            rfcProveedor: "string",
            razonProveedor: "string",
            paisDestino: "string",
            rfcCliente: "string",
            razonCliente: "string",
            domicilio: "string",
            testado: true,
            idProductoP: "string",
            descTestado: "string"
            }
        ],
        listaProyecto: [
            {
            idProyecto: "string",
            tipoDocumento: "string",
            descDocumento: "string",
            otro: "string",
            fechaIncio: "string",
            fechaFin: "string",
            firmante: {
                idFirmante: "string",
                rfc: "string",
                razonSocial: "string",
                claveFraccion: "string"
            },
            testado: "string",
            idProducto: "stri",
            descTestado: "string"
            }
        ],
        nicoDtos: storeData.nicoTablaDatosImportacion,
        proyectosClientes: [
            {
            paisOrigen: "",
            rfcProveedor: "",
            razonProveedor: "",
            paisDestino: "ARGELIA (REPUBLICA DEMOCRATICA Y POPULAR DE)",
            rfcClient: "GDFGFDHGJGHJGH",
            razonCliente: "D FFGSDFSFSDF",
            domicilioCliente: "",
            testado: false,
            fecFinVigencia: null
            }
        ],
        complemento: {
            anexoII: "NO SENSIBLE",
            tipo: "EXPORTACION",
            unidadMedida: "Kilogramo",
            categoria: "TICAT.MP",
            descripcion: "DEJ JLFKDSFDSFSDF",
            valorMensual: "12",
            valorAnual: "432",
            volumenMensual: "5435",
            volumenAnual: "534",
            testado: true,
            fecFinVigencia: null,
            volumenAnualSolicitado: null
        }
        }
    ],
    claveModalidadActual: "MOD-123",
    datosCertificacion: "CERT-001",
    montoImportaciones: 500000,
    factorAmpliacion: 1.2,
    proyeccion: 750000,
    trabajadores: 150,
    id_solicitud: 12345,
    discriminator_value: "80203",
    certificacion_sat: "CERTIFICADO",
    unidadAdministrativaRepresentacionFederal: {
        clave: "string",
        idDependencia: 0,
        claveEntidad: "string",
        claveUnidadAdminR: "string",
        ideTipoUnidadAdministrativa: "string",
        nivel: 0,
        acronimo: "string",
        nombre: "string",
        descripcion: "string",
        fechaInicioVigencia: "2025-09-08",
        fechaFinVigencia: "2025-09-08",
        activo: true,
        idDireccion: 0,
        fronteriza: true
    },
    programaAutorizadoEconomia: {
        idProgramaAutorizado: 0,
        folioPrograma: "string",
        tipoPrograma: "string",
        movimientoProgramaSE: "string",
        rfc: "MTR8012148K9",
        anioPrograma: 0,
        resolucionId: 0,
        unidadAdministrativaId: 0,
        fechaInicioVigencia: "2025-09-08",
        fechaFinVigencia: "2025-09-08",
        actividadProductiva: "string",
        fechaSuspension: "2025-09-08"
    },
    datosPrograma: (storeData.immexTableDatos ?? []).map(item => ({
      consecutivo: item.consecutivo ?? '',
      idProducto: "",
      numeroPrograma: item.numeroPrograma ?? '',
      fraccion: item.fraccion ?? '',
      descripcion: item.descripcion ?? '',
      umt: item.umt ?? '',
      cantidadAutorizada: item.cantidadAutorizada ?? '',
      fechaInicio: item.fechaInicio ?? '',
      fechaFin: item.fechaFin ?? '',
      idMercanciaSub: 8080,
      testado: "",
      claveUsuario: ""
    })),
    domicilio: {
        idDomicilio: 0,
        calle: "string",
        numExterior: "string",
        numInterior: "string",
        codigoPostal: "string",
        informacionExtra: "string",
        clave: "string",
        cveLocalidad: "string",
        cveDelegMun: "string",
        cveEntidad: "string",
        cvePais: "string",
        ciudad: "string",
        telefono: "string",
        fax: "string",
        municipio: "string",
        colonia: "string",
        descUbicacion: "string",
        cveCatalogo: "string",
        telefonos: "string",
        tipoDomicilio: 0,
        coloniaEntity: {
        nombre: ""
        },
        delegacionMunicipio: {
        cveDelegMun: ""
        },
        entidadFederativa: {
        cveEntidad: ""
        },
        pais: {
        cvePais: ""
        }
    },
    solicitante: {
        idPersonaPersonaSolicitudR: 0,
        idSolicitud: 202734824,
        nombre: "",
        apellidoMaterno: "",
        apellidoPaterno: "",
        razonSocial: "AGRICOLA ALPE S DE RL DE CV",
        rfc: "AAL0409235E6",
        curp: "",
        ideTipoPersonaSol: "TIPERS.SL",
        correoElectronico: "vucem.soporte.aplicativo@ultrasist.com.mx",
        cedulaProfesional: "",
        nss: "",
        telefono: "8154563",
        descripcionGiro: "Siembra, cultivo y cosecha de papa",
        cvePaisOrigen: "",
        idDireccionSol: 260833725,
        tipoPatenteAgente: "",
        recif: "",
        puesto: "",
        tipoAgente: "",
        numeroPatente: "",
        numeroIdentificacionFiscal: "",
        personaMoral: false,
        extranjero: false,
        organismoPublico: false,
        cveUsuario: "AAL0409235E6",
        paginaWeb: "",
        ideGenerica1: "",
        rfcExtranjero: "",
        codAutorizacion: "",
        actividadProductiva: "",
        estadoEvaluacionEntidad: "AUTORIZADO",
        estadoEntidad: "AUTORIZADO",
        original: false,
        modificado: false,
        numeroRegistro: "",
        concentimientoInstalacionRecuperacion: false,
        cveCatalogo: "",
        alquilado: false,
        volumenAlmacenaje: 0,
        capacidadAlmacenaje: 0,
        descripcionDetalladaActividadEconomica: "",
        activo: false,
        generico1: false,
        area: "",
        cveNacionalidad: "",
        clasificacionArancelaria: "",
        infoAdicional: false,
        montoImportacion: 0,
        montoExportacion: 0,
        pctParticAccionaria: 0,
        ampliacionModelos: false,
        ampliacionPaises: false,
        fecFallecimiento: "2025-09-07"
    }
    }
}
