import { ImmexRegistroState } from "../estados/tramites/tramite80203.store";

export function buildGuardarPayload(storeData: ImmexRegistroState): unknown {
  return {
        "tipoDeSolicitud": "guardar",
        "idSolicitud": 0,
        "idTipoTramite": 80203,
        "rfc": "AAL0409235E6",
        "cveUnidadAdministrativa": "8203",
        "costoTotal": 10000.5,
        "certificadoSerialNumber": "1234567890ABCDEF",
        "certificado": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A",
        "numeroFolioTramiteOriginal": "TRM-2023-00001",
        "nombre": "Juan",
        "apPaterno": "Pérez",
        "apMaterno": "López",
        "telefono": "5551234567",
        "discriminatorValue": "80203",
        "programaImmex": {
            "folioPrograma": "string",
            "tipoPrograma": "string",
            "movimientoProgramaSE": "string",
            "rfc": "AAL0409235E6",
            "anioPrograma": 0,
            "fechaInicioVigencia": "2025-09-03",
            "fechaFinVigencia": "2025-09-03",
            "actividadProductiva": "string",
            "fechaSuspension": "2025-09-03",
            "modalidad": "string",
            "numeroImmex": "string",
            "resolucionId": 0,
            "unidadAdministrativaId": 0
        },
        "productoExportacionDtoList": storeData.fraccionTablaDatos.map((fraccion)=>{
            return {   
                "claveProductoExportacion":1,
                "testado": true,
                "claveServicioImmex": null,
                "tipoFraccion": "TIPD.EX",
                "visible": true,
                "fraccionPadre": null,
                "replica": true,
                "activo": true,
                "idProductoExp": null,
                "fraccionCompuesta": null,
                "cveSector": null,
                "idSectorProsecSol": 0,
                "blnFraccionSeleccionada": 0,
                "descripcionTestado": null,
                "fraccionArancelaria": {
                    "activo": fraccion.fraccionArancelaria.activo,
                    "activoAnexo28": true,
                    "capitulo": fraccion.fraccionArancelaria.capitulo,
                    "claveCategoria": "string",
                    "claveFraccionPadre": "string",
                    "claveProductoExportacion": 0,
                    "cveCapituloFraccion": "string",
                    "cveFraccion": fraccion.fraccionArancelaria.cveFraccion,
                    "cvePartidaFraccion": "string",
                    "cveSubPartidaFraccion": "string",
                    "cveUsuario": fraccion.fraccionArancelaria.cveUsuario,
                    "decretoImmex": true,
                    "descripcion": fraccion.fraccionArancelaria.descripcion,
                    "descripcionCategoria": "string",
                    "descripcionFraccionPadre": "string",
                    "descripcionServicio": "string",
                    "descripcionTestado": "string",
                    "descripcionUsuario": fraccion.fraccionArancelaria.descripcionUsuario,
                    "exenta": true,
                    "fechaCaptura": fraccion.fraccionArancelaria.fechaCaptura,
                    "fechaFinVigencia": "2025-09-07T12:43:35.647Z",
                    "fechaInicioVigencia": fraccion.fraccionArancelaria.fechaInicioVigencia,
                    "fraccionCompuesta": "string",
                    "fraccionConcatenada": "string",
                    "fraccionPadre": fraccion.fraccionArancelaria.fraccionPadre,
                    "idFraccion": "string",
                    "idProducto": "stri",
                    "idProductoPadre": fraccion.fraccionArancelaria.idProductoPadre,
                    "mensaje": "string",
                    "nicoDtos": fraccion.fraccionArancelaria.nicoDtos,
                    "partida": fraccion.fraccionArancelaria.partida,
                    "rowID": "string",
                    "subPartida": fraccion.fraccionArancelaria.subPartida,
                    "testado": fraccion.fraccionArancelaria.testado,
                    "tipoFraccion": "string",
                    "tipoOperacion": "string",
                    "umt": fraccion.fraccionArancelaria.umt,
                    "unidadMedida": fraccion.fraccionArancelaria.unidadMedida,
                    "valorMonedaAnual": "string",
                    "valorMonedaMensual": "string",
                    "valorProduccionAnual": "string",
                    "valorProduccionAnualSolicitada": "string",
                    "valorProduccionMensual": "string"
                }
            }
        }),
        "mercanciaImportacion": [
            {
                "claveMercanciaImportacion": 0,
                "testado": 0,
                "tipoFraccion": "string",
                "visible": true,
                "fraccionPadre": "string",
                "blnFraccionSeleccionada": 0,
                "claveFraccionPadre": "string",
                "fraccionCompuesta": "string",
                "descripcionTestado": "string",
                "unidadMedida": "string",
                "tipoOperacion": "string",
                "valorMonedaMensual": "string",
                "valorMonedaAnual": storeData.candiadAnual,
                "valorProduccionMensual": storeData.capacidadPeriodo,
                "valorProduccionAnual": storeData.candidadPorPeriodo,
                "valorProduccionAnualSolicitada": "string",
                "categoria": "string",
                "mensaje": "string",
                "umt": "string",
                "claveCategoria": "string",
                "descripcionUsuario": "string",
                "descripcionFraccionPadre": "string",
                "idProductoPadre": "string",
                "idProducto": "stri",
                "permisoPadre": "string",
                "fraccionArancelaria": {
                    "capitulo": "61",
                    "partida": "6103",
                    "subPartida": "610323",
                    "descripcion": "De fibras sinteticas.",
                    "fechaCaptura": "2010-01-01",
                    "fechaInicioVigencia": "2010-01-01",
                    "fechaFinVigencia": null,
                    "cveUsuario": "RECE670302IU0",
                    "cveCapituloFraccion": "61",
                    "cvePartidaFraccion": "03",
                    "cveSubPartidaFraccion": "23",
                    "activo": true,
                    "activoAnexo28": false,
                    "decretoImmex": true,
                    "fraccionPadre": "string",
                    "descripcionFraccionPadre": "string",
                    "tipoFraccion": "string",
                    "exenta": true,
                    "fraccionCompuesta": "string",
                    "claveFraccionPadre": "string",
                    "unidadMedida": "string",
                    "fraccionConcatenada": "string",
                    "descripcionTestado": "string",
                    "testado": true,
                    "tipoOperacion": "string",
                    "valorMonedaMensual": "string",
                    "valorMonedaAnual": "string",
                    "valorProduccionMensual": "string",
                    "valorProduccionAnual": "string",
                    "valorProduccionAnualSolicitada": "string",
                    "claveCategoria": "string",
                    "descripcionCategoria": "string",
                    "mensaje": "string",
                    "descripcionUsuario": "string",
                    "umt": "string",
                    "idFraccion": "string",
                    "idProducto": "stri",
                    "idProductoPadre": "string",
                    "claveProductoExportacion": 0,
                    "descripcionServicio": "string",
                    "rowID": "string",
                    "cveFraccion": "61032301"
                },
                "listaProveedores": [
                    {
                        "idProveedor": "string",
                        "paisOrigen": "string",
                        "rfcProveedor": "string",
                        "razonProveedor": "string",
                        "paisDestino": "string",
                        "rfcCliente": "string",
                        "razonCliente": "string",
                        "domicilio": "string",
                        "testado": true,
                        "idProductoP": "string",
                        "descTestado": "string"
                    }
                ],
                "listaProyecto": [
                    {
                        "idProyecto": "string",
                        "tipoDocumento": "string",
                        "descDocumento": "string",
                        "otro": "string",
                        "fechaIncio": "string",
                        "fechaFin": "string",
                        "firmante": {
                            "idFirmante": "string",
                            "rfc": "string",
                            "razonSocial": "string",
                            "claveFraccion": "string"
                        },
                        "testado": "string",
                        "idProducto": "stri",
                        "descTestado": "string"
                    }
                ],
                "nicoDtos": storeData.nicoTablaDatosImportacion,
                "proyectosClientes": [
                    {
                        "paisOrigen": "",
                        "rfcProveedor": "",
                        "razonProveedor": "",
                        "paisDestino": "ARGELIA (REPUBLICA DEMOCRATICA Y POPULAR DE)",
                        "rfcClient": "GDFGFDHGJGHJGH",
                        "razonCliente": "D FFGSDFSFSDF",
                        "domicilioCliente": "",
                        "testado": false,
                        "fecFinVigencia": null
                    }
                ],
                "complemento": {
                    "anexoII": "NO SENSIBLE",
                    "tipo": "EXPORTACION",
                    "unidadMedida": "Kilogramo",
                    "categoria": "TICAT.MP",
                    "descripcion": "DEJ JLFKDSFDSFSDF",
                    "valorMensual": "12",
                    "valorAnual": "432",
                    "volumenMensual": "5435",
                    "volumenAnual": "534",
                    "testado": true,
                    "fecFinVigencia": null,
                    "volumenAnualSolicitado": null
                }
            }
        ],
        "fraccionesSensibles": [
            {
                "claveSencible": 0,
                "complemento": "00001",
                "unidadMedidaTarifaria": "1",
                "cantidad": "300000.0",
                "valor": "20000.00",
                "fraccionPadre": "02101999",
                "descUnidadMedida": null,
                "fechaInicioVigencia": "2025-09-07",
                "fechaFinVigencia": "2025-09-07",
                "cveFraccion": "string"
            }
        ],
        "claveModalidadActual": "MOD-123",
        "datosCertificacion": "CERT-001",
        "montoImportaciones": 500000,
        "factorAmpliacion": 1.2,
        "proyeccion": 750000,
        "trabajadores": 150,
        "id_solicitud": 12345,
        "discriminator_value": "80203",
        "certificacion_sat": "CERTIFICADO",
        "unidadAdministrativaRepresentacionFederal": {
            "clave": "string",
            "idDependencia": 0,
            "claveEntidad": "string",
            "claveUnidadAdminR": "string",
            "ideTipoUnidadAdministrativa": "string",
            "nivel": 0,
            "acronimo": "string",
            "nombre": "string",
            "descripcion": "string",
            "fechaInicioVigencia": "2025-09-08",
            "fechaFinVigencia": "2025-09-08",
            "activo": true,
            "idDireccion": 0,
            "fronteriza": true
        },
        "programaAutorizadoEconomia": {
            "idProgramaAutorizado": 0,
            "folioPrograma": "string",
            "tipoPrograma": "string",
            "movimientoProgramaSE": "string",
            "rfc": "MTR8012148K9",
            "anioPrograma": 0,
            "resolucionId": 0,
            "unidadAdministrativaId": 0,
            "fechaInicioVigencia": "2025-09-08",
            "fechaFinVigencia": "2025-09-08",
            "actividadProductiva": "string",
            "fechaSuspension": "2025-09-08"
        },
        "datosPrograma": storeData.immexTableDatos.map(item => ({
            "consecutivo": item.consecutivo,
            "idProducto": item.idProducto,
            "numeroPrograma": item.numeroPrograma,
            "fraccion": "61032301",
            "descripcion": item.descripcion,
            "umt": item.umt,
            "cantidadAutorizada": item.cantidadAutorizada,
            "fechaInicio": item.fechaInicio,
            "fechaFin": item.fechaFin,
            "idMercanciaSub": item.idMercanciaSub,
            "testado": item.testado,
            "claveUsuario": item.claveUsuario
        })),
        "domicilio": {},
        "solicitante": {}
    }
}
