export const COOKIE = {
  NOMBRE_COOKIE_ID_USUARIO: 'sg-id-user',
  NOMBRE_COOKIE_ROL: 'sg-rol',
  NOMBRE_COOKIE_TOKEN: 'sg-token',
  NOMBRE_COOKIE_USUARIO: 'sg-usuario',
  NOMBRE_COOKIE_RFC: 'sg-rfc',
}

export const CATALOGOS_ID = {
  CAT_TIPO_SOL: 1,
  CAT_PAISES: 2,
  CAT_ADUANAS: 3,
  CAT_SECCION_ADUANAS: 4,
  DATOS_GNRLS_SOL: 5,
  CAT_TIPO_DOCUMENTO: 6,
  CAT_TIPO_OPERACION: 7
}

export const TIPO_PERSONA = {
  FISICA_NACIONAL: 1,
  MORAL_NACIONAL: 2,
  FISICA_EXTRANJERA: 3,
  MORAL_EXTRANJERA: 4
}
