# Dockerfile

# Stage 1: Build the Angular app
FROM node:22-slim AS node
WORKDIR /app

# Install dependencies
# COPY . .
COPY *.json ./
COPY apps ./apps
COPY libs ./libs
# RUN pwd && ls -a /app
# RUN npm ci

# Install Nx CLI globally
RUN npm install -g nx

# Build the app using Nx.
RUN npm install --force --no-audit --no-package-lock
# RUN pwd && ls -a /app
# RUN pwd && ls -a /app/.nx
# RUN npm i webpack@5.91.0
# RUN npx nx reset
ENV NX_VERBOSE_LOGGING=true
# ENV NX_DEAMON=true
ARG NODE_ENV
RUN echo "Building semarnat image for environment: $NODE_ENV"
RUN npx nx build semarnat --configuration=$NODE_ENV --base-href=/semarnat/ --skip-nx-cache --verbose
# RUN pwd && ls -a /app/dist/apps/semarnat

# Stage 2: Serve with Nginx
FROM nginx:alpine-slim
COPY ./apps/semarnat/nginx.conf /etc/nginx/nginx.conf
COPY --from=node app/dist/apps/semarnat /usr/share/nginx/html