# Expose the deployment using a Service
apiVersion: v1
kind: Service
metadata:
  name: modulefederation-inah-microfront-service-dev
spec:
  selector:
    app: modulefederation-inah-microfront-dev
  ports:
    - protocol: TCP
      port: 4221
      targetPort: 80
  type: NodePort
