name: Build and Deploy profepa App

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'apps/profepa/Dockerfile.dev**'
      - 'docker/**'
      - '.github/workflows/docker-k8s-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/vucem30-dev/dockerized-modulefederation-profepa-microfront
      TAG: 1.0.1

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG -f apps/profepa/Dockerfile.dev .
          docker push $IMAGE_NAME:$TAG
      
      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Decode Kubeconfig and Set up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Set image and deploy to Kubernetes
        run: |
          microk8s kubectl apply -f profepa-microfront-deployment-dev.yaml
          microk8s kubectl rollout restart deployment modulefederation-profepa-microfront-deployment-dev -n default
