name: Build and Deploy profepa App

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'apps/profepa/Dockerfile.dev**'
      - 'docker/**'
      - 'k8s/profepa-microfront/**'
      - '.github/workflows/docker-k8s-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/vucem30-dev/dockerized-modulefederation-profepa-microfront
      TAG: 1.0.1

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG -f apps/profepa/Dockerfile.dev .
          docker push $IMAGE_NAME:$TAG
      - name: Execute remote command (last one)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_SRV_IP }}
          username: ${{ secrets.REMOTE_SRV_USER }}
          key: ${{ secrets.REMOTE_SRV_PRIV_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/v30/deploy/deploy-microfront/profepa-microfront/
            microk8s kubectl apply -f profepa-microfront-deployment-dev.yaml
            microk8s kubectl rollout restart deployment modulefederation-profepa-microfront-deployment-dev -n default
            microk8s kubectl get pods | grep profepa
