name: Quality Lint and Test AGA

on:
  pull_request:
    # Solo ejecutar cuando los PRs van hacia ramas principales
    branches: [ "develop", "staging", "production" ]
    paths:
      - 'apps/**'
      - 'libs/**'
      - 'package.json'
      - 'nx.json'
      - '.eslintrc.json'
  push:
    branches: [ "develop", "staging", "production" ]
    paths:
      - 'apps/**'
      - 'libs/**'
      - 'package.json'
      - 'nx.json'
      - '.eslintrc.json'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      NX_SKIP_POSTINSTALL: 1   # Evita la ejecución del postinstall de Nx
    steps:
      # Obtiene el código de tu repositorio.
      - name: Checkout repository
        uses: actions/checkout@v3

      #  Configura la versión de Node.js requerida (22.14.0).
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
          
      - name: Instalar NX globalmente
        run: npm install -g nx@19.3.1
        
      # Instala el módulo nativo requerido para Linux.
      - name: Install native binding for Nx on Linux
        run: npm install @nx/nx-linux-x64-gnu
        
      # Instala el binding nativo de SWC para Linux (necesario para la compilación)
      - name: Install SWC native binding for Linux
        run: npm install @swc/core-linux-x64-gnu
        

      # 3. Instala las dependencias usando --force, tal como lo haces localmente.
      - name: Install dependencies
        run: |
          npm install --force
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name:  Run lint on AGA
        run: npx nx lint aga

      - name: Run tests on AGA
        run: npx nx run aga:test

      - name:  Run lint on agace
        run: npx nx lint agace

      - name: Run tests on agace
        run: npx nx run agace:test

      - name:  Run lint on agricultura
        run: npx nx lint agricultura

      - name: Run tests on agricultura
        run: npx nx run agricultura:test

      - name:  Run lint on se
        run: npx nx lint se

      - name: Run tests on se
        run: npx nx run se:test

      - name:  Run lint on semarnat
        run: npx nx lint semarnat

      - name: Run tests on semarnat
        run: npx nx run semarnat:test

      - name:  Run lint on cofepris
        run: npx nx lint cofepris

      - name: Run tests on cofepris
        run: npx nx run cofepris:test

      - name:  Run lint on sener
        run: npx nx lint sener

      - name: Run tests on sener
        run: npx nx run sener:test

      - name:  Run lint on amecafe
        run: npx nx lint amecafe

      - name: Run tests on amecafe
        run: npx nx run amecafe:test

      - name:  Run lint on inbal
        run: npx nx lint inbal

      - name: Run tests on inbal
        run: npx nx run inbal:test

      - name:  Run lint on sedena
        run: npx nx lint sedena

      - name: Run tests on sedena
        run: npx nx run sedena:test

      - name:  Run lint on profepa
        run: npx nx lint profepa

      - name: Run tests on profepa
        run: npx nx run profepa:test

      - name:  Run lint on inah
        run: npx nx lint inah

      - name: Run tests on inah
        run: npx nx run inah:test

      - name:  Run lint on crt
        run: npx nx lint crt

      - name: Run tests on crt
        run: npx nx run crt:test

      - name:  Run lint on stps
        run: npx nx lint stps

      - name: Run tests on stps
        run: npx nx run stps:test

      - name:  Run lint on bandejas
        run: npx nx lint bandejas

      - name: Run tests on bandejas
        run: npx nx run bandejas:test
